/* GM Security Systems - Static Pro Demo v12 Inventory Focus */
const Logic = (() => {
  const money = n => '$' + Number(n || 0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
  const lbp = n => 'LBP ' + Math.round(Number(n || 0)).toLocaleString();
  const BEIRUT_TZ = 'Asia/Beirut';
  const today = () => {
    const parts = new Intl.DateTimeFormat('en-CA', { timeZone: BEIRUT_TZ, year:'numeric', month:'2-digit', day:'2-digit' }).formatToParts(new Date());
    const y = parts.find(p=>p.type==='year')?.value;
    const m = parts.find(p=>p.type==='month')?.value;
    const d = parts.find(p=>p.type==='day')?.value;
    return `${y}-${m}-${d}`;
  };
  const beirutDateTime = () => new Intl.DateTimeFormat('en-LB', { timeZone: BEIRUT_TZ, dateStyle:'medium', timeStyle:'short' }).format(new Date());
  const dateAddDays = (iso, days) => {
    const base = iso ? new Date(iso + 'T12:00:00Z') : new Date();
    base.setUTCDate(base.getUTCDate() + Number(days || 0));
    return base.toISOString().slice(0,10);
  };
  const maxDate = (...dates) => dates.filter(Boolean).sort().pop() || '';
  const docSeq = id => Number(String(id||'').match(/(\d+)$/)?.[1] || 0);
  const uid = p => p + '-' + Math.random().toString(36).slice(2,7).toUpperCase();
  const docNo = (prefix, list) => prefix + '-' + String((list?.length || 0) + 1).padStart(4,'0');
  const calcItems = items => (items || []).reduce((a,i)=>a + Number(i.qty||0)*Number(i.price||0),0);
  const discountAmount = (subtotal,type,value) => String(type||'amount')==='percent' ? subtotal * Number(value||0) / 100 : Number(value||0);
  const calcDocTotal = doc => { const sub = calcItems(doc.items||[]); return Math.max(0, sub - discountAmount(sub, doc.discountType || 'amount', doc.discountValue ?? doc.discount ?? 0)); };
  const blobText = obj => JSON.stringify(obj).toLowerCase();
  const deepSearch = (obj, q) => !q || blobText(obj).includes(String(q).toLowerCase());
  const invoiceStatus = inv => Number(inv.balance||0) <= 0 ? 'Paid' : Number(inv.paid||0) > 0 ? 'Partial' : (inv.due && inv.due < today() ? 'Overdue' : 'Unpaid');
  function defaultData(){
    return {
      settings:{user:'admin', pass:'gm1234', autoLock:30, lighter:true, exchangeRate:89500},
      clients:[
        {id:uid('CL'),name:'ABC Trading Co.',phone:'+961 70 123456',email:'info@abc.com',location:'Beirut',status:'Active',notes:''},
        {id:uid('CL'),name:'Green Valley Hotel',phone:'+961 71 654321',email:'gvh@hotel.com',location:'Jounieh',status:'Active',notes:''},
        {id:uid('CL'),name:'City Mall',phone:'+961 76 999888',email:'city@mall.com',location:'Sin El Fil',status:'Active',notes:''}
      ],
      inventory:[
        {id:uid('IT'),partNo:'CAM-4MP',name:'IP Camera 4MP',description:'IP Camera 4MP',brand:'',category:'CCTV',unit:'pcs',qty:14,min:5,cost:110,price:180,supplier:'',location:'Shelf A'},
        {id:uid('IT'),partNo:'DVR-8CH',name:'DVR 8CH',description:'DVR 8CH',brand:'',category:'CCTV',unit:'pcs',qty:3,min:2,cost:280,price:420,supplier:'',location:'Shelf A'},
        {id:uid('IT'),partNo:'SRV-INSTALL',name:'Installation & Configuration',description:'Installation & Configuration',brand:'',category:'Service',unit:'job',qty:999,min:0,cost:0,price:150,supplier:'',location:''},
        {id:uid('IT'),partNo:'CAB-CAT6',name:'CAT6 Cable',description:'CAT6 Cable',brand:'',category:'Network',unit:'rolls',qty:8,min:3,cost:30,price:45,supplier:'',location:'Store'}
      ],
      stockMovements:[],
      suppliers:[{id:uid('SU'),name:'TechLine Lebanon',contact:'Ali Hassan',phone:'+961 70 777111',category:'CCTV & Alarm',balance:2400,status:'Active'}],
      quotes:[
        {id:'QT-0001',clientId:'',client:'City Mall',date:'2026-06-29',validUntil:'2026-07-06',status:'Pending',items:[{description:'IP Camera 4MP',qty:10,price:180},{description:'Installation & Configuration',qty:1,price:550}],discount:0,notes:'',terms:'50% down payment, balance upon installation.',total:2350},
        {id:'QT-0002',clientId:'',client:'Green Valley Hotel',date:'2026-06-29',validUntil:'2026-07-06',status:'Draft',items:[{description:'WiFi AP Indoor',qty:4,price:150},{description:'Cabling & Setup',qty:1,price:300}],discount:0,notes:'',terms:'',total:900}
      ],
      invoices:[
        {id:'INV-0001',clientId:'',client:'ABC Trading Co.',date:'2026-06-25',due:'2026-07-25',status:'Unpaid',items:[{description:'CCTV Maintenance Visit',qty:1,price:850}],discount:0,total:850,paid:0,balance:850,notes:''},
        {id:'INV-0002',clientId:'',client:'Green Valley Hotel',date:'2026-06-20',due:'2026-07-20',status:'Paid',items:[{description:'WiFi AP Indoor',qty:4,price:350},{description:'Cabling & Setup',qty:1,price:1000}],discount:0,total:2400,paid:2400,balance:0,notes:''}
      ],
      receipts:[{id:'RC-0001',invoiceId:'INV-0002',client:'Green Valley Hotel',date:'2026-06-21',method:'Cash',amount:2400,balance:0,notes:'Full payment received.'}],
      visits:[{id:uid('V'),client:'ABC Trading Co.',type:'CCTV Maintenance',date:'2026-06-30',time:'10:00',status:'Scheduled',notes:''}]
    }
  }
  function normalizeInvoice(inv){ inv.total = calcDocTotal(inv); inv.balance = Math.max(0, Number(inv.total||0) - Number(inv.paid||0)); inv.status = invoiceStatus(inv); return inv; }
  return {money,lbp,today,dateAddDays,maxDate,docSeq,uid,docNo,calcItems,discountAmount,calcDocTotal,deepSearch,defaultData,normalizeInvoice};
})();

const App = {
  data:null,page:'dashboard',editing:null,sessionTimer:null,lastActivity:Date.now(),
  pages:{dashboard:['Dashboard','Business overview and quick actions'],quotations:['Quotations','Create, search, print and convert quotes'],invoices:['Invoices','Billing, receipts and payment tracking'],receipts:['Receipts','Payments and reprints'],clients:['Clients','Client accounts and statements'],suppliers:['Suppliers','Vendors and balances'],inventory:['Inventory','Items, services and stock'],visits:['Visits','Scheduling and field work'],reports:['Reports','Profit, loss and balances'],settings:['Settings','Security and backup']},
  nav:[['Main'],['dashboard','⊞','Dashboard'],['Sales'],['quotations','📋','Quotations'],['invoices','🧾','Invoices'],['receipts','💵','Receipts'],['Operations'],['clients','👥','Clients'],['suppliers','🏭','Suppliers'],['visits','📅','Visits'],['inventory','📦','Inventory'],['Finance'],['reports','📊','Reports'],['settings','⚙','Settings']],
  init(){ this.load(); this.bindLogin(); this.renderNav(); if(localStorage.getItem('gm_session')==='1') this.unlock(); else this.lock(); },
  load(){ try{this.data=JSON.parse(localStorage.getItem('gm_data_v5'))||Logic.defaultData()}catch(e){this.data=Logic.defaultData()} this.migrate(); this.save(); },
  migrate(){
    this.data.settings=this.data.settings||{user:'admin',pass:'gm1234',autoLock:30,lighter:true,exchangeRate:89500}; if(!this.data.settings.exchangeRate) this.data.settings.exchangeRate=89500;
    this.data.clients=(this.data.clients||[]).map((c,i)=>({id:c.id||Logic.uid('CL'),accountNo:c.accountNo||('CL-'+String(i+1).padStart(4,'0')),businessName:c.businessName||c.companyName||c.name||'',companyName:c.companyName||c.businessName||c.name||'',firstName:c.firstName||'',lastName:c.lastName||'',contactName:c.contactName||[c.firstName,c.lastName].filter(Boolean).join(' '),phone:c.phone||'',email:c.email||'',location:c.location||'',currency:c.currency||'USD',status:c.status||'Active',notes:c.notes||''}));
    this.data.inventory=(this.data.inventory||[]).map((it,i)=>({id:it.id||Logic.uid('IT'),partNo:it.partNo||it.itemNo||'',name:it.name||it.description||'',description:it.description||it.name||'',brand:it.brand||'',category:it.category||'Service',unit:it.unit||'pcs',qty:Number(it.qty||0),min:Number(it.min||0),cost:Number(it.cost||0),price:Number(it.price||0),supplier:it.supplier||'',location:it.location||it.shelf||''}));
    this.data.stockMovements=(this.data.stockMovements||[]).map(m=>({id:m.id||Logic.uid('MV'),itemId:m.itemId||'',itemNo:m.itemNo||'',description:m.description||'',type:m.type||'Adjustment',date:m.date||Logic.today(),qty:Number(m.qty||0),fromQty:Number(m.fromQty||0),toQty:Number(m.toQty||0),supplier:m.supplier||'',client:m.client||'',invoiceId:m.invoiceId||'',reason:m.reason||'',notes:m.notes||''}));
    this.data.quotes=this.data.quotes||[]; this.data.invoices=this.data.invoices||[]; this.data.receipts=this.data.receipts||[];
  },
  save(){ localStorage.setItem('gm_data_v5',JSON.stringify(this.data)); },
  bindLogin(){
    const ok=()=>this.tryLogin(); document.getElementById('loginBtn').onclick=ok; document.getElementById('loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')ok()}); document.getElementById('logoutBtn').onclick=()=>this.lock(true);
    ['click','keydown','touchstart'].forEach(ev=>document.addEventListener(ev,()=>this.lastActivity=Date.now())); setInterval(()=>this.checkAutoLock(),30000);
  },
  tryLogin(){ const u=loginUser.value.trim(), p=loginPass.value; if(u===this.data.settings.user && p===this.data.settings.pass){localStorage.setItem('gm_session','1'); loginError.textContent=''; loginPass.value=''; this.unlock()} else loginError.textContent='Wrong username or password'; },
  unlock(){ loginScreen.classList.add('hidden'); app.classList.remove('hidden'); this.lastActivity=Date.now(); this.render(); },
  lock(manual=false){ localStorage.removeItem('gm_session'); app.classList.add('hidden'); loginScreen.classList.remove('hidden'); if(manual) this.toast('Logged out'); },
  checkAutoLock(){ if(localStorage.getItem('gm_session')!=='1')return; const min=Number(this.data.settings.autoLock||30); if(Date.now()-this.lastActivity > min*60000) this.lock(true); },
  toast(t){ const el=document.getElementById('toast'); el.textContent=t; el.style.display='block'; clearTimeout(this._toast); this._toast=setTimeout(()=>el.style.display='none',2600); },
  renderNav(){ const build=(target,bottom=false)=>{target.innerHTML=this.nav.map(n=>n.length===1&&!bottom?`<div class="nav-section">${n[0]}</div>`:n.length===1?'':`<div class="nav-item ${this.page===n[0]?'active':''}" onclick="App.go('${n[0]}')"><span>${n[1]}</span><span>${n[2]}</span></div>`).join('')}; build(nav); build(bottomNav,true); },
  go(p){ this.page=p; this.renderNav(); this.render(); },
  render(){ const [t,s]=this.pages[this.page]; pageTitle.textContent=t; pageSub.textContent=s; const map={dashboard:this.dashboard,quotations:this.quotations,invoices:this.invoices,receipts:this.receipts,clients:this.clients,suppliers:this.suppliers,inventory:this.inventory,visits:this.visits,reports:this.reports,settings:this.settings}; view.innerHTML=map[this.page].call(this); },
  rowActions(type,id){ return `<div class="row-actions"><button class="btn ghost mini" onclick="App.viewDoc('${type}','${id}')">View</button><button class="btn ghost mini" onclick="App.edit('${type}','${id}')">Edit</button><button class="btn danger mini" onclick="App.del('${type}','${id}')">Delete</button></div>` },
  dashboard(){ const d=this.data, inv=d.invoices.map(Logic.normalizeInvoice); const revenue=inv.reduce((a,i)=>a+Number(i.paid||0),0), invoiced=inv.reduce((a,i)=>a+Number(i.total||0),0), outstanding=inv.reduce((a,i)=>a+Number(i.balance||0),0); const estCost=d.inventory.reduce((a,i)=>a+Number(i.cost||0)*Math.min(Number(i.qty||0),1),0); const profit=revenue-estCost; const lastQ=[...d.quotes].slice(-5).reverse(), lastI=[...inv].slice(-5).reverse(); const byClient={}; inv.forEach(i=>byClient[i.client]=(byClient[i.client]||0)+Number(i.total||0)); const top=Object.entries(byClient).sort((a,b)=>b[1]-a[1])[0];
    return `<div class="quick-grid"><button class="btn primary" onclick="App.openDocForm('invoice')">+ New Invoice</button><button class="btn primary" onclick="App.openDocForm('quote')">+ New Quotation</button><button class="btn" onclick="App.openClientForm()">+ New Client</button><button class="btn green" onclick="App.openReceiptForm()">+ New Receipt</button></div>
    <div class="circles card"><div class="circle"><div><strong>${Logic.money(revenue)}</strong><span>Collected</span></div></div><div class="circle"><div><strong>${Logic.money(invoiced)}</strong><span>Total Invoiced</span></div></div><div class="circle"><div><strong>${Logic.money(profit)}</strong><span>Net Profit</span></div></div><div class="circle"><div><strong>${Logic.money(outstanding)}</strong><span>Outstanding</span></div></div></div>
    <div class="grid stats" style="margin-top:16px"><div class="stat-card"><div class="bar"></div><div class="stat-num">${d.quotes.filter(q=>q.status==='Pending'||q.status==='Sent').length}</div><div class="stat-label">Pending Quotes</div></div><div class="stat-card"><div class="bar"></div><div class="stat-num">${inv.filter(i=>i.status==='Overdue').length}</div><div class="stat-label">Overdue Invoices</div></div><div class="stat-card"><div class="bar"></div><div class="stat-num">${top?top[0]:'—'}</div><div class="stat-label">Top Selling Client</div></div><div class="stat-card"><div class="bar"></div><div class="stat-num">${d.inventory.filter(i=>Number(i.qty)<=Number(i.min)).length}</div><div class="stat-label">Low Stock</div></div></div>
    <div class="grid two" style="margin-top:16px"><div class="card"><h3 class="section-title">Last 5 Quotations</h3>${lastQ.map(q=>this.listRow(q.id,q.client,Logic.money(q.total),q.status)).join('')||'No quotations'}</div><div class="card"><h3 class="section-title">Last 5 Invoices</h3>${lastI.map(i=>this.listRow(i.id,i.client,Logic.money(i.total),i.status)).join('')||'No invoices'}</div></div>`},
  listRow(a,b,c,status){return `<div class="list-row"><div><b>${a}</b><div class="muted small">${b}</div></div><div class="right"><b>${c}</b><br><span class="badge ${status}">${status}</span></div></div>`},
  searchToolbar(type,btn){ return `<div class="toolbar"><input class="search" id="search_${type}" placeholder="Search by client, number, item, amount, notes..." oninput="App.renderList('${type}')"><div>${btn||''}</div></div><div id="list_${type}"></div>`},
  quotations(){ setTimeout(()=>this.renderList('quotes'),0); return this.searchToolbar('quotes',`<button class="btn primary" onclick="App.openDocForm('quote')">+ New Quotation</button>`) },
  invoices(){ setTimeout(()=>this.renderList('invoices'),0); return this.searchToolbar('invoices',`<button class="btn primary" onclick="App.openDocForm('invoice')">+ New Invoice</button>`) },
  receipts(){ setTimeout(()=>this.renderList('receipts'),0); return this.searchToolbar('receipts',`<button class="btn green" onclick="App.openReceiptForm()">+ New Receipt</button>`) },
  clients(){ setTimeout(()=>this.renderList('clients'),0); return this.searchToolbar('clients',`<button class="btn primary" onclick="App.openClientForm()">+ New Client</button>`) },
  suppliers(){ setTimeout(()=>this.renderList('suppliers'),0); return this.searchToolbar('suppliers',`<button class="btn primary" onclick="App.openSupplierForm()">+ Supplier</button>`) },
  inventory(){ setTimeout(()=>this.renderInventoryTab('items'),0); return `<div class="inv-tabs"><button class="btn primary" id="tab_items" onclick="App.renderInventoryTab('items')">Items</button><button class="btn ghost" id="tab_movements" onclick="App.renderInventoryTab('movements')">Movements</button><button class="btn ghost" id="tab_low" onclick="App.renderInventoryTab('low')">Low Stock</button></div><div id="inventoryContent"></div>` },
  visits(){ setTimeout(()=>this.renderList('visits'),0); return this.searchToolbar('visits',`<button class="btn primary" onclick="App.openVisitForm()">+ Schedule Visit</button>`) },
  renderInventoryTab(tab='items'){
    const wrap=document.getElementById('inventoryContent'); if(!wrap)return;
    ['items','movements','low'].forEach(t=>{const b=document.getElementById('tab_'+t); if(b){b.className='btn '+(t===tab?'primary':'ghost')}});
    if(tab==='items'){
      wrap.innerHTML=`<div class="toolbar"><input class="search" id="search_inventory2" placeholder="Search item #, description, brand, category, supplier, location..." oninput="App.renderInventoryItems()"><div class="row-actions"><button class="btn primary" onclick="App.openItemForm()">+ Item / Service</button><button class="btn green" onclick="App.openStockForm('in')">Stock In</button><button class="btn orange" onclick="App.openStockForm('out')">Stock Out</button><button class="btn ghost" onclick="App.openStockForm('adjustment')">Adjustment</button></div></div><div id="inventoryItemsTable"></div>`;
      this.renderInventoryItems();
    } else if(tab==='movements'){
      wrap.innerHTML=`<div class="toolbar"><input class="search" id="search_movements" placeholder="Search item #, type, supplier, client, invoice, notes..." oninput="App.renderMovements()"><div><button class="btn green" onclick="App.openStockForm('in')">Stock In</button><button class="btn orange" onclick="App.openStockForm('out')">Stock Out</button><button class="btn ghost" onclick="App.openStockForm('adjustment')">Adjustment</button></div></div><div id="movementsTable"></div>`;
      this.renderMovements();
    } else {
      const rows=this.data.inventory.filter(i=>Number(i.qty||0)<=Number(i.min||0));
      wrap.innerHTML=`<div class="card"><h3 class="section-title">Low Stock / Reorder</h3>${this.table(['Item #','Description','Supplier','Location','Stock','Min','Action'], rows.map(i=>[i.partNo||'',i.description||i.name||'',i.supplier||'',i.location||'',`${i.qty} ${i.unit||''}`,i.min||0,`<button class="btn green mini" onclick="App.openStockForm('in','${i.id}')">Stock In</button>`]))}</div>`;
    }
  },
  renderInventoryItems(){ const q=document.getElementById('search_inventory2')?.value||''; const rows=this.data.inventory.filter(i=>Logic.deepSearch(i,q)); const el=document.getElementById('inventoryItemsTable'); if(!el)return; el.innerHTML=this.table(['Item #','Description','Category','Brand','Supplier','Location','Stock','Min','Cost','Sell',''],rows.map(i=>[i.partNo||'',i.description||i.name||'',i.category||'',i.brand||'',i.supplier||'',i.location||'',`${i.qty} ${i.unit||''}`,i.min||0,Logic.money(i.cost),Logic.money(i.price),`<div class="row-actions"><button class="btn green mini" onclick="App.openStockForm('in','${i.id}')">In</button><button class="btn orange mini" onclick="App.openStockForm('out','${i.id}')">Out</button><button class="btn ghost mini" onclick="App.openStockForm('adjustment','${i.id}')">Adj</button><button class="btn ghost mini" onclick="App.openItemForm('${i.id}')">Edit</button><button class="btn danger mini" onclick="App.del('inventory','${i.id}')">Delete</button></div>`])); },
  movementSigned(m){ if(m.type==='Stock In')return '+'+Number(m.qty||0); if(m.type==='Stock Out')return '-'+Number(m.qty||0); return String(Number(m.toQty||0)-Number(m.fromQty||0)); },
  renderMovements(){ const q=document.getElementById('search_movements')?.value||''; const rows=[...this.data.stockMovements].reverse().filter(m=>Logic.deepSearch(m,q)); const el=document.getElementById('movementsTable'); if(!el)return; el.innerHTML=this.table(['Date','Type','Item #','Description','Qty','From','To','Supplier/Client','Ref','Notes'],rows.map(m=>[m.date,m.type,m.itemNo,m.description,this.movementSigned(m),m.fromQty,m.toQty,[m.supplier,m.client].filter(Boolean).join(' / '),m.invoiceId||m.reason||'',m.notes||''])); },
  reports(){ return `<div class="grid two"><div class="card"><h3 class="section-title">Profit & Loss</h3>${this.dashboard().match(/<div class="circles card">[\s\S]*?<\/div><\/div><\/div><\/div><\/div>/)?.[0]||''}</div><div class="card"><h3 class="section-title">Outstanding Balances</h3>${this.data.invoices.map(Logic.normalizeInvoice).filter(i=>i.balance>0).map(i=>this.listRow(i.id,i.client,Logic.money(i.balance),i.status)).join('')||'Clear'}</div></div>`},
  settings(){ return `<div class="card"><h3 class="section-title">Security</h3><div class="form-grid"><div class="field"><label>Username</label><input id="setUser" value="${this.data.settings.user}"></div><div class="field"><label>Password</label><input id="setPass" value="${this.data.settings.pass}"></div><div class="field"><label>Auto lock minutes</label><input id="setLock" type="number" value="${this.data.settings.autoLock||30}"></div><div class="field"><label>Default Exchange Rate LBP / USD</label><input id="setRate" type="number" value="${this.data.settings.exchangeRate||89500}"></div></div><button class="btn primary" onclick="App.saveSettings()">Save Settings</button><p class="muted small">Default: 1 USD = 89,500 LBP. All document dates use Lebanon time zone (Asia/Beirut). Date backdating is limited: a document cannot be dated before the previous same-type document, and converted invoices cannot be dated before their source quotation.</p></div><div class="card"><h3 class="section-title">Backup</h3><button class="btn ghost" onclick="App.exportBackup()">Export Backup JSON</button> <label class="btn ghost">Import Backup <input type="file" hidden onchange="App.importBackup(event)"></label> <button class="btn danger" onclick="App.resetDemo()">Reset Demo Data</button></div>`},
  saveSettings(){ this.data.settings.user=setUser.value.trim()||'admin'; this.data.settings.pass=setPass.value||'gm1234'; this.data.settings.autoLock=Number(setLock.value||30); this.data.settings.exchangeRate=Number(setRate.value||89500); this.save(); this.toast('Settings saved') },
  renderList(type){ const q=document.getElementById('search_'+type)?.value||''; let rows=this.data[type].filter(x=>Logic.deepSearch(x,q)); const el=document.getElementById('list_'+type); if(!el)return; if(type==='quotes') el.innerHTML=this.table(['Quote #','Client','Date','Amount','Status',''],rows.map(x=>[x.id,x.client,x.date,Logic.money(x.total),`<span class="badge ${x.status}">${x.status}</span>`,this.rowActions('quote',x.id)+`<button class="btn green mini" onclick="App.convertQuote('${x.id}')">→ Invoice</button>`]));
    if(type==='invoices') el.innerHTML=this.table(['Invoice #','Client','Due','Total','Paid','Balance','Status',''],rows.map(x=>{x=Logic.normalizeInvoice(x); return [x.id,x.client,x.due,Logic.money(x.total),Logic.money(x.paid),Logic.money(x.balance),`<span class="badge ${x.status}">${x.status}</span>`,this.rowActions('invoice',x.id)+`<button class="btn green mini" onclick="App.openReceiptForm('${x.id}')">Receipt</button>`]}));
    if(type==='receipts') el.innerHTML=this.table(['Receipt #','Client','Invoice','Date','Method','Amount',''],rows.map(x=>[x.id,x.client,x.invoiceId||'Manual',x.date,x.method,Logic.money(x.amount),`<div class="row-actions"><button class="btn ghost mini" onclick="App.viewDoc('receipt','${x.id}')">View/Print</button><button class="btn ghost mini" onclick="App.edit('receipt','${x.id}')">Edit</button><button class="btn danger mini" onclick="App.del('receipt','${x.id}')">Delete</button></div>`]));
    if(type==='clients') el.innerHTML=this.table(['Client','Phone','Location','Balance','Status',''],rows.map(c=>[c.name,c.phone,c.location,Logic.money(this.clientBalance(c.name)),`<span class="badge ${c.status}">${c.status}</span>`,`<div class="row-actions"><button class="btn ghost mini" onclick="App.statementById('${c.id}')">Statement</button><button class="btn ghost mini" onclick="App.openClientForm('${c.id}')">Edit</button><button class="btn danger mini" onclick="App.del('client','${c.id}')">Delete</button></div>`]));
    if(type==='inventory') el.innerHTML=this.table(['Item #','Description','Category','Stock','Cost','Sell','Status',''],rows.map(i=>[i.partNo||'',i.description||i.name,i.category,`${i.qty} ${i.unit}`,Logic.money(i.cost),Logic.money(i.price),`<span class="badge ${Number(i.qty)<=Number(i.min)?'Low':'OK'}">${Number(i.qty)<=Number(i.min)?'Low':'OK'}</span>`,`<button class="btn ghost mini" onclick="App.openItemForm('${i.id}')">Edit</button><button class="btn danger mini" onclick="App.del('inventory','${i.id}')">Delete</button>`]));
    if(type==='suppliers') el.innerHTML=this.table(['Supplier','Contact','Phone','Category','Balance','Status',''],rows.map(s=>[s.name,s.contact,s.phone,s.category,Logic.money(s.balance),`<span class="badge ${s.status}">${s.status}</span>`,`<div class="row-actions"><button class="btn ghost mini" onclick="App.openSupplierForm('${s.id}')">Edit</button><button class="btn danger mini" onclick="App.del('supplier','${s.id}')">Delete</button></div>`]));
    if(type==='visits') el.innerHTML=this.table(['Client','Type','Date','Time','Status','Notes',''],rows.map(v=>[v.client,v.type,v.date,v.time,`<span class="badge ${v.status}">${v.status}</span>`,v.notes||'',`<div class="row-actions"><button class="btn ghost mini" onclick="App.openVisitForm('${v.id}')">Edit</button><button class="btn danger mini" onclick="App.del('visit','${v.id}')">Delete</button></div>`]));
  },
  table(head,rows){ return `<div class="card table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>` },
  clientBalance(name){ return this.data.invoices.map(Logic.normalizeInvoice).filter(i=>i.client===name).reduce((a,i)=>a+Number(i.balance||0),0) },
  modal(title,body){ modalRoot.innerHTML=`<div class="modal-back" onclick="App.closeModal(event)"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h3>${title}</h3><button class="btn ghost" onclick="App.closeModal()">✕</button></div><div class="modal-body">${body}</div></div></div>` },
  closeModal(e){ if(e&&e.target.className!=='modal-back')return; modalRoot.innerHTML=''; },
  clientDisplay(c){ return c.businessName || c.companyName || c.name || [c.firstName,c.lastName].filter(Boolean).join(' ') || c.phone || c.id; },
  clientOptions(sel=''){return this.data.clients.map(c=>{const n=this.clientDisplay(c); return `<option value="${n}" ${sel===n?'selected':''}>${n}${c.location?' · '+c.location:''}</option>`}).join('')},
  itemOptions(){return this.data.inventory.map(i=>`<option value="${i.partNo||''}" data-price="${i.price}">${i.partNo||''} — ${i.description||i.name}</option>`).join('')},
  getClientByName(name){ return this.data.clients.find(c=>this.clientDisplay(c)===name || c.name===name || c.businessName===name || c.companyName===name); },
  getItemByText(txt){ return this.data.inventory.find(x=>(x.description||x.name||'').toLowerCase()===String(txt||'').toLowerCase() || String(x.partNo||'').toLowerCase()===String(txt||'').toLowerCase()); },
  openDocForm(kind,id){
    const isQ=kind==='quote', list=isQ?'quotes':'invoices';
    const old=id?this.data[list].find(x=>x.id===id):null;
    const doc=old||{id:Logic.docNo(isQ?'QT':'INV',this.data[list]),client:'',date:Logic.today(),due:Logic.dateAddDays(Logic.today(),30),validUntil:Logic.dateAddDays(Logic.today(),7),status:isQ?'Draft':'Unpaid',items:[{partNo:'',description:'',qty:1,price:0,saved:false}],discount:0,paid:0,notes:'',terms:''};
    this.editing={kind,id:doc.id};
    this.formItems=JSON.parse(JSON.stringify(doc.items||[])).map(x=>({partNo:x.partNo||'',description:x.description||x.name||'',qty:x.qty||1,price:x.price||0,saved:!!(x.saved||this.getItemByText(x.description||x.name))}));
    this.modal(isQ?'Quotation':'Invoice',`
      <div class="form-grid three">
        <div class="field"><label>Number</label><input id="docId" value="${doc.id}"></div>
        <div class="field"><label>Client / Business</label><select id="docClient"><option value="">Select client</option>${this.clientOptions(doc.client)}</select></div>
        <div class="field"><label>Quick Client</label><button class="btn" onclick="App.toggleQuickClient()">+ Add Client Here</button></div>
        <div class="field"><label>Date</label><input id="docDate" type="date" value="${doc.date}" min="${this.minAllowedDocDate(list,doc)}" onchange="App.onDocDateChange()"><small class="muted">${this.minAllowedDocDate(list,doc)?'Earliest allowed: '+this.minAllowedDocDate(list,doc):'Beirut date'}</small></div>
        <div class="field"><label>${isQ?'Valid Until':'Due Date'}</label><input id="docDue" type="date" value="${isQ?doc.validUntil:doc.due}" min="${doc.date}"></div>
        <div class="field"><label>Status</label><select id="docStatus">${(isQ?['Draft','Sent','Pending','Accepted','Rejected','Converted']:['Unpaid','Partial','Paid','Overdue']).map(st=>`<option ${doc.status===st?'selected':''}>${st}</option>`).join('')}</select></div>
      </div>
      <div id="quickClientPanel" class="quick-panel hidden">${this.quickClientHtml()}</div>
      <div class="items-box" id="itemsBox"></div>
      <div class="line-actions"><button class="btn ghost" onclick="App.addLine()">+ Add Line</button><span class="small muted">New custom items must be saved before adding another line.</span></div>
      <div class="totals"><div><span>Discount Type</span><select id="docDiscountType" onchange="App.recalcForm()"><option value="amount" ${(doc.discountType||'amount')==='amount'?'selected':''}>Fixed $</option><option value="percent" ${doc.discountType==='percent'?'selected':''}>Percent %</option></select></div><div><span>Discount</span><input id="docDiscount" type="number" value="${doc.discountValue ?? doc.discount ?? 0}" oninput="App.recalcForm()" style="width:110px"></div>${!isQ?`<div><span>Paid</span><input id="docPaid" type="number" value="${doc.paid||0}" oninput="App.recalcForm()" style="width:110px"></div>`:''}<div><span>Total</span><b id="docTotal">$0</b></div></div>
      <div class="field"><label>Notes / Terms</label><textarea id="docNotes">${doc.notes||doc.terms||''}</textarea></div>
      ${!isQ?`<label class="stock-check"><input type="checkbox" id="docDeductStock"> Deduct stock from Inventory now <span class="muted small">(use when items are delivered/sold)</span></label>`:''}
      <button class="btn primary" onclick="App.saveDoc('${kind}')">Save ${isQ?'Quotation':'Invoice'}</button>`);
    this.drawLines();
  },
  quickClientHtml(){ return `<div class="section-title">New Client Details</div><div class="form-grid three"><div class="field"><label>Account Number</label><input id="qcAccount" value="CL-${String((this.data.clients||[]).length+1).padStart(4,'0')}"></div><div class="field"><label>Company / Business Name</label><input id="qcBusiness" placeholder="Business name"></div><div class="field"><label>Currency</label><select id="qcCurrency"><option>USD</option><option>LBP</option><option>EUR</option></select></div><div class="field"><label>Exchange Rate LBP / USD</label><input id="qcRate" type="number" value="${this.data.settings.exchangeRate||89500}"></div><div class="field"><label>First Name</label><input id="qcFirst" placeholder="Contact first name"></div><div class="field"><label>Last Name</label><input id="qcLast" placeholder="Contact last name"></div><div class="field"><label>Phone</label><input id="qcPhone" placeholder="+961..."></div><div class="field"><label>Email</label><input id="qcEmail" placeholder="email optional"></div><div class="field"><label>Location</label><input id="qcLocation" placeholder="City / area"></div><div class="field"><label>Status</label><select id="qcStatus"><option>Active</option><option>Inactive</option></select></div><div class="field full-span"><label>Notes</label><textarea id="qcNotes" placeholder="Client notes"></textarea></div></div><div class="row-actions"><button class="btn primary" onclick="App.saveQuickClient()">Save Client</button><button class="btn ghost" onclick="App.toggleQuickClient(false)">Cancel</button></div>`},
  toggleQuickClient(show=true){ const p=document.getElementById('quickClientPanel'); if(!p)return; p.classList.toggle('hidden',!show); },
  saveQuickClient(){
    const business=(qcBusiness.value||'').trim(), first=(qcFirst.value||'').trim(), last=(qcLast.value||'').trim();
    const display=business || [first,last].filter(Boolean).join(' ');
    if(!display){this.toast('Add business name or contact name first'); return;}
    const c={id:Logic.uid('CL'),accountNo:qcAccount.value.trim()||Logic.uid('CL'),businessName:business,companyName:business,name:display,firstName:first,lastName:last,contactName:[first,last].filter(Boolean).join(' '),phone:qcPhone.value.trim(),email:qcEmail.value.trim(),location:qcLocation.value.trim(),currency:qcCurrency.value,exchangeRate:Number(qcRate.value||this.data.settings.exchangeRate||89500),status:qcStatus.value,notes:qcNotes.value};
    this.data.clients.push(c); this.save();
    const sel=document.getElementById('docClient'); const n=this.clientDisplay(c); sel.innerHTML=`<option value="">Select client</option>${this.clientOptions(n)}`; sel.value=n;
    this.toggleQuickClient(false); this.toast('Client saved to Clients');
  },
  drawLines(){
    itemsBox.innerHTML=this.formItems.map((it,i)=>`<div class="item-line pro-line ${it.saved?'saved-line':''}">
      <div class="field"><label>Item #</label><input list="itemList" value="${it.partNo||''}" oninput="App.formItems[${i}].partNo=this.value;App.autofillByItemNo(${i},this.value)" placeholder="ex: DS-7616NXI-K2"></div>
      <div class="field desc-field"><label>Description</label><input value="${it.description||''}" oninput="App.formItems[${i}].description=this.value;App.markUnsaved(${i})" placeholder="Type/edit description"></div>
      <div class="field"><label>Qty</label><input type="number" min="1" value="${it.qty||1}" oninput="App.formItems[${i}].qty=this.value;App.updateLineAmount(${i});App.recalcForm()"></div>
      <div class="field"><label>Unit Price $</label><input type="number" min="0" value="${it.price||0}" oninput="App.formItems[${i}].price=this.value;App.updateLineAmount(${i});App.recalcForm()"></div>
      <div class="field"><label>Amount</label><input id="lineAmount${i}" disabled value="${Logic.money(Number(it.qty||0)*Number(it.price||0))}"></div>
      <div class="line-buttons"><button class="btn green mini" onclick="App.saveLineItem(${i})">Save Item</button><button class="btn danger mini" onclick="App.formItems.splice(${i},1);App.drawLines()">✕</button><div class="small ${it.saved?'ok-text':'warn-text'}">${it.saved?'Saved':'New item - save first'}</div></div>
    </div>`).join('')+`<datalist id="itemList">${this.itemOptions()}</datalist>`; this.recalcForm();
  },
  markUnsaved(i){ const it=this.formItems[i]; const item=this.data.inventory.find(x=>String(x.partNo||'').toLowerCase()===String(it.partNo||'').toLowerCase() && String(it.partNo||'').trim()); it.saved=!!item; },
  autofillByItemNo(i,val){ const item=this.data.inventory.find(x=>String(x.partNo||'').toLowerCase()===String(val||'').toLowerCase()); if(item){this.formItems[i].partNo=item.partNo||''; this.formItems[i].description=item.description||item.name; this.formItems[i].price=item.price; this.formItems[i].saved=true; this.drawLines()} else {this.formItems[i].saved=false; this.updateLineAmount(i); this.recalcForm()} },
  updateLineAmount(i){ const el=document.getElementById('lineAmount'+i); const it=this.formItems[i]||{}; if(el) el.value=Logic.money(Number(it.qty||0)*Number(it.price||0)); },
  lineIsValid(it){ return String(it.partNo||'').trim() && String(it.description||'').trim() && Number(it.qty||0)>0 && Number(it.price||0)>0; },
  addLine(){
    const last=this.formItems[this.formItems.length-1];
    if(last && (!this.lineIsValid(last) || !last.saved)){ this.toast('Complete Item #, description, price, then Save Item before adding another line'); return; }
    this.formItems.push({partNo:'',description:'',qty:1,price:0,saved:false}); this.drawLines();
  },
  saveLineItem(i){
    const it=this.formItems[i];
    if(!this.lineIsValid(it)){this.toast('Item #, description, qty and price are required before saving item'); return;}
    let found=this.data.inventory.find(x=>String(x.partNo||'').toLowerCase()===String(it.partNo||'').toLowerCase());
    if(found){ found.description=it.description; found.name=it.description; found.price=Number(it.price); }
    else { found={id:Logic.uid('IT'),partNo:String(it.partNo).trim(),name:it.description,description:it.description,brand:'',category:'Service / Item',unit:'pcs',qty:0,min:0,cost:0,price:Number(it.price),supplier:'',location:''}; this.data.inventory.push(found); }
    it.partNo=found.partNo; it.description=found.description||found.name; it.price=found.price; it.saved=true; this.save(); this.drawLines(); this.toast('Item saved to Inventory');
  },
  recalcForm(){ const sub=Logic.calcItems(this.formItems); const total=Math.max(0, sub-Logic.discountAmount(sub, document.getElementById('docDiscountType')?.value||'amount', document.getElementById('docDiscount')?.value||0)); const el=document.getElementById('docTotal'); if(el)el.textContent=Logic.money(total); },
  quickClient(){ this.toggleQuickClient(true); },
  quickItem(){ this.addLine(); },
  saveDoc(kind){
    const isQ=kind==='quote', list=isQ?'quotes':'invoices';
    if(!docClient.value){this.toast('Select or add a client first'); return;}
    if(!this.formItems.length){this.toast('Add at least one item'); return;}
    for(const it of this.formItems){ if(!this.lineIsValid(it)){this.toast('Every item needs description, qty and price'); return;} if(!it.saved){this.toast('Save every new item to Inventory before saving document'); return;} }
    const clientObj=this.getClientByName(docClient.value);
    let doc={id:docId.value.trim(),client:docClient.value,clientId:clientObj?.id||'',currency:clientObj?.currency||'USD',exchangeRate:clientObj?.exchangeRate||this.data.settings.exchangeRate||89500,date:docDate.value,status:docStatus.value,items:this.formItems.map(({partNo,description,qty,price,saved})=>({partNo,description,qty:Number(qty),price:Number(price),saved:true})),discountType:docDiscountType.value,discountValue:Number(docDiscount.value||0),discount:Logic.discountAmount(Logic.calcItems(this.formItems),docDiscountType.value,docDiscount.value||0),notes:docNotes.value};
    if(isQ){doc.validUntil=docDue.value; doc.terms=docNotes.value; if(!this.validateDocDates('quotes',doc)) return; doc.total=Logic.calcDocTotal(doc)}else{doc.due=docDue.value; doc.paid=Number(docPaid.value||0); if(!this.validateDocDates('invoices',doc)) return; Logic.normalizeInvoice(doc)}
    const idx=this.data[list].findIndex(x=>x.id===this.editing.id); if(idx>=0)this.data[list][idx]=doc; else this.data[list].push(doc);
    if(!isQ && document.getElementById('docDeductStock')?.checked) this.deductInvoiceStock(doc);
    this.save(); this.closeModal(); this.render(); this.toast((isQ?'Quotation':'Invoice')+' saved');
  },
  openClientForm(id){ const c=id?this.data.clients.find(x=>x.id===id):{id:Logic.uid('CL'),accountNo:'CL-'+String((this.data.clients||[]).length+1).padStart(4,'0'),businessName:'',companyName:'',firstName:'',lastName:'',phone:'',email:'',location:'',currency:'USD',exchangeRate:this.data.settings.exchangeRate||89500,status:'Active',notes:''}; this.modal('Client Account',`<div class="form-grid three"><div class="field"><label>Account Number</label><input id="cAccount" value="${c.accountNo||''}"></div><div class="field"><label>Company / Business Name</label><input id="cBusiness" value="${c.businessName||c.companyName||c.name||''}"></div><div class="field"><label>Currency</label><select id="cCurrency"><option ${c.currency==='USD'?'selected':''}>USD</option><option ${c.currency==='LBP'?'selected':''}>LBP</option><option ${c.currency==='EUR'?'selected':''}>EUR</option></select></div><div class="field"><label>Exchange Rate LBP / USD</label><input id="cRate" type="number" value="${c.exchangeRate||this.data.settings.exchangeRate||89500}"></div><div class="field"><label>First Name</label><input id="cFirst" value="${c.firstName||''}"></div><div class="field"><label>Last Name</label><input id="cLast" value="${c.lastName||''}"></div><div class="field"><label>Phone</label><input id="cPhone" value="${c.phone||''}"></div><div class="field"><label>Email</label><input id="cEmail" value="${c.email||''}"></div><div class="field"><label>Location</label><input id="cLoc" value="${c.location||''}"></div><div class="field"><label>Status</label><select id="cStatus"><option ${c.status==='Active'?'selected':''}>Active</option><option ${c.status==='Inactive'?'selected':''}>Inactive</option></select></div><div class="field full-span"><label>Notes</label><textarea id="cNotes">${c.notes||''}</textarea></div></div><button class="btn primary" onclick="App.saveClient('${c.id}')">Save Client</button>`); },
  saveClient(id){ const business=cBusiness.value.trim(), first=cFirst.value.trim(), last=cLast.value.trim(), display=business||[first,last].filter(Boolean).join(' '); if(!display){this.toast('Business name or contact name is required');return;} const c={id,accountNo:cAccount.value.trim()||id,businessName:business,companyName:business,name:display,firstName:first,lastName:last,contactName:[first,last].filter(Boolean).join(' '),phone:cPhone.value,email:cEmail.value,location:cLoc.value,currency:cCurrency.value,exchangeRate:Number(cRate.value||this.data.settings.exchangeRate||89500),status:cStatus.value,notes:cNotes.value}; const i=this.data.clients.findIndex(x=>x.id===id); if(i>=0)this.data.clients[i]=c; else this.data.clients.push(c); this.save(); this.closeModal(); this.render(); },
  openItemForm(id){ const it=id?this.data.inventory.find(x=>x.id===id):{id:Logic.uid('IT'),partNo:'',description:'',name:'',brand:'',category:'Service',unit:'pcs',qty:0,min:0,cost:0,price:0,supplier:'',location:''}; this.modal('Item / Service',`<div class="form-grid three"><div class="field"><label>Item #</label><input id="iPart" value="${it.partNo||''}"></div><div class="field"><label>Description</label><input id="iName" value="${it.description||it.name||''}"></div><div class="field"><label>Brand</label><input id="iBrand" value="${it.brand||''}" placeholder="Hikvision / Ajax..."></div><div class="field"><label>Category</label><input id="iCat" value="${it.category||''}"></div><div class="field"><label>Supplier</label><input id="iSupplier" value="${it.supplier||''}" list="supplierList"></div><div class="field"><label>Location / Shelf</label><input id="iLocation" value="${it.location||''}" placeholder="Shelf A / Van / Store"></div><div class="field"><label>Unit</label><input id="iUnit" value="${it.unit||'pcs'}"></div><div class="field"><label>Qty</label><input id="iQty" type="number" value="${it.qty||0}"></div><div class="field"><label>Min Qty</label><input id="iMin" type="number" value="${it.min||0}"></div><div class="field"><label>Cost $</label><input id="iCost" type="number" value="${it.cost||0}"></div><div class="field"><label>Selling Price $</label><input id="iPrice" type="number" value="${it.price||0}"></div></div><datalist id="supplierList">${this.data.suppliers.map(s=>`<option value="${s.name}">`).join('')}</datalist><button class="btn primary" onclick="App.saveItem('${it.id}')">Save Item</button>`); },
  saveItem(id){ const desc=iName.value.trim(); const part=iPart.value.trim(); if(!part){this.toast('Item # is required');return;} if(!desc){this.toast('Description is required');return;} const old=this.data.inventory.find(x=>x.id===id); const oldQty=Number(old?.qty||0); const newQty=Number(iQty.value||0); const it={id,partNo:part,name:desc,description:desc,brand:iBrand.value.trim(),category:iCat.value,unit:iUnit.value,qty:newQty,min:Number(iMin.value||0),cost:Number(iCost.value),price:Number(iPrice.value),supplier:iSupplier.value.trim(),location:iLocation.value.trim()}; const i=this.data.inventory.findIndex(x=>x.id===id); if(i>=0)this.data.inventory[i]=it; else this.data.inventory.push(it); if(old && oldQty!==newQty){ this.addMovementRecord({item:it,type:'Adjustment',qty:Math.abs(newQty-oldQty),fromQty:oldQty,toQty:newQty,reason:'Manual item edit',notes:'Qty changed in item form'}); } this.save(); this.closeModal(); this.render(); this.toast('Item saved'); },
  
  openSupplierForm(id=''){ const s=id?this.data.suppliers.find(x=>x.id===id):{id:Logic.uid('SU'),name:'',contact:'',phone:'',category:'',balance:0,status:'Active',notes:''}; this.modal(id?'Edit Supplier':'Supplier',`<div class="form-grid three"><div class="field"><label>Supplier Name</label><input id="sName" value="${s.name||''}"></div><div class="field"><label>Contact Person</label><input id="sContact" value="${s.contact||''}"></div><div class="field"><label>Phone</label><input id="sPhone" value="${s.phone||''}"></div><div class="field"><label>Category</label><input id="sCat" value="${s.category||''}"></div><div class="field"><label>Balance $</label><input id="sBalance" type="number" value="${s.balance||0}"></div><div class="field"><label>Status</label><select id="sStatus"><option ${s.status==='Active'?'selected':''}>Active</option><option ${s.status==='Inactive'?'selected':''}>Inactive</option></select></div><div class="field full-span"><label>Notes</label><textarea id="sNotes">${s.notes||''}</textarea></div></div><button class="btn primary" onclick="App.saveSupplier('${s.id}')">Save Supplier</button>`); },
  saveSupplier(id){ const item={id,name:sName.value.trim(),contact:sContact.value.trim(),phone:sPhone.value.trim(),category:sCat.value.trim(),balance:Number(sBalance.value||0),status:sStatus.value,notes:sNotes.value}; if(!item.name){this.toast('Supplier name required');return;} const i=this.data.suppliers.findIndex(x=>x.id===id); if(i>=0)this.data.suppliers[i]=item; else this.data.suppliers.push(item); this.save(); this.closeModal(); this.render(); this.toast('Supplier saved'); },
  openVisitForm(id=''){ const v=id?this.data.visits.find(x=>x.id===id):{id:Logic.uid('V'),client:'',type:'',date:Logic.today(),time:'09:00',status:'Scheduled',technician:'',notes:''}; this.modal(id?'Edit Visit':'Schedule Visit',`<div class="form-grid three"><div class="field"><label>Client</label><select id="vClient"><option value="">Select client</option>${this.clientOptions(v.client)}</select></div><div class="field"><label>Visit Type</label><input id="vType" value="${v.type||''}" placeholder="CCTV Maintenance"></div><div class="field"><label>Date</label><input id="vDate" type="date" value="${v.date||Logic.today()}"></div><div class="field"><label>Time</label><input id="vTime" type="time" value="${v.time||'09:00'}"></div><div class="field"><label>Status</label><select id="vStatus">${['Scheduled','In Progress','Done','Cancelled'].map(st=>`<option ${v.status===st?'selected':''}>${st}</option>`).join('')}</select></div><div class="field"><label>Technician</label><input id="vTech" value="${v.technician||''}"></div><div class="field full-span"><label>Notes</label><textarea id="vNotes">${v.notes||''}</textarea></div></div><button class="btn primary" onclick="App.saveVisit('${v.id}')">Save Visit</button>`); },
  saveVisit(id){ const item={id,client:vClient.value,type:vType.value.trim(),date:vDate.value,time:vTime.value,status:vStatus.value,technician:vTech.value.trim(),notes:vNotes.value}; if(!item.client||!item.type){this.toast('Client and visit type required');return;} const i=this.data.visits.findIndex(x=>x.id===id); if(i>=0)this.data.visits[i]=item; else this.data.visits.push(item); this.save(); this.closeModal(); this.render(); this.toast('Visit saved'); },
  addMovementRecord(m){ this.data.stockMovements=this.data.stockMovements||[]; const item=m.item||this.data.inventory.find(x=>x.id===m.itemId)||{}; this.data.stockMovements.push({id:Logic.uid('MV'),itemId:item.id||m.itemId||'',itemNo:item.partNo||m.itemNo||'',description:item.description||item.name||m.description||'',type:m.type||'Adjustment',date:m.date||Logic.today(),qty:Number(m.qty||0),fromQty:Number(m.fromQty||0),toQty:Number(m.toQty||0),supplier:m.supplier||'',client:m.client||'',invoiceId:m.invoiceId||'',reason:m.reason||'',notes:m.notes||''}); },
  openStockForm(mode='in', itemId=''){
    const type=mode==='in'?'Stock In':mode==='out'?'Stock Out':'Adjustment';
    const it=this.data.inventory.find(x=>x.id===itemId)||{};
    this.modal(type,`<div class="form-grid three"><div class="field"><label>Item</label><select id="mvItem"><option value="">Select item</option>${this.data.inventory.map(i=>`<option value="${i.id}" ${i.id===itemId?'selected':''}>${i.partNo||''} — ${i.description||i.name||''} (${i.qty||0} ${i.unit||''})</option>`).join('')}</select></div><div class="field"><label>Date</label><input id="mvDate" type="date" value="${Logic.today()}"></div><div class="field"><label>${mode==='adjustment'?'New Counted Qty':'Quantity'}</label><input id="mvQty" type="number" min="0" value="0"></div><div class="field"><label>Supplier</label><input id="mvSupplier" value="${it.supplier||''}" list="supplierList2"></div><div class="field"><label>Client / Job</label><input id="mvClient" value=""></div><div class="field"><label>Reason</label><select id="mvReason">${['Purchase','Used in invoice','Used for installation','Return','Stock count','Correction','Other'].map(r=>`<option>${r}</option>`).join('')}</select></div><div class="field full-span"><label>Notes</label><textarea id="mvNotes" placeholder="Optional notes"></textarea></div></div><datalist id="supplierList2">${this.data.suppliers.map(s=>`<option value="${s.name}">`).join('')}</datalist><button class="btn primary" onclick="App.saveStockMovement('${mode}')">Save ${type}</button>`);
  },
  saveStockMovement(mode){ const id=mvItem.value; const item=this.data.inventory.find(x=>x.id===id); if(!item){this.toast('Select item first');return;} const from=Number(item.qty||0); let qty=Number(mvQty.value||0); if(qty<0){this.toast('Qty cannot be negative');return;} let to=from; let type=mode==='in'?'Stock In':mode==='out'?'Stock Out':'Adjustment'; if(mode==='in')to=from+qty; else if(mode==='out')to=Math.max(0,from-qty); else {to=qty; qty=Math.abs(to-from);} item.qty=to; this.addMovementRecord({item,type,date:mvDate.value,qty,fromQty:from,toQty:to,supplier:mvSupplier.value.trim(),client:mvClient.value.trim(),reason:mvReason.value,notes:mvNotes.value}); this.save(); this.closeModal(); this.render(); this.toast(type+' saved'); },
  deductInvoiceStock(doc){ (doc.items||[]).forEach(li=>{ const item=this.data.inventory.find(x=>String(x.partNo||'').toLowerCase()===String(li.partNo||'').toLowerCase()); if(!item)return; if(String(item.category||'').toLowerCase().includes('service'))return; const from=Number(item.qty||0), qty=Number(li.qty||0), to=Math.max(0,from-qty); item.qty=to; this.addMovementRecord({item,type:'Stock Out',date:doc.date||Logic.today(),qty,fromQty:from,toQty:to,client:doc.client,invoiceId:doc.id,reason:'Used in invoice',notes:'Auto deducted from invoice'}); }); },
  convertQuote(id){ const q=this.data.quotes.find(x=>x.id===id); if(!q)return; const inv=Logic.normalizeInvoice({id:Logic.docNo('INV',this.data.invoices),client:q.client,date:Logic.maxDate(Logic.today(),q.date),due:Logic.dateAddDays(Logic.maxDate(Logic.today(),q.date),30),sourceQuoteId:q.id,currency:q.currency||'USD',exchangeRate:q.exchangeRate||this.data.settings.exchangeRate||89500,items:q.items,discountType:q.discountType||'amount',discountValue:q.discountValue??q.discount??0,discount:q.discount,total:q.total,paid:0,balance:q.total,status:'Unpaid',notes:'Converted from '+q.id}); this.data.invoices.push(inv); q.status='Converted'; this.save(); this.render(); this.toast('Converted to invoice'); },
  openReceiptForm(invoiceId='', receiptId=''){ const rec=receiptId?this.data.receipts.find(r=>r.id===receiptId):null; const selectedInvId=rec?.invoiceId||invoiceId||''; const inv=this.data.invoices.find(i=>i.id===selectedInvId); const client=inv?this.getClientByName(inv.client):this.getClientByName(rec?.client||''); const rate=rec?.exchangeRate||inv?.exchangeRate||client?.exchangeRate||this.data.settings.exchangeRate||89500; this.modal(receiptId?'Edit Receipt':'Receipt',`<div class="form-grid"><div class="field"><label>Invoice</label><select id="rInv"><option value="">Manual</option>${this.data.invoices.map(i=>`<option value="${i.id}" ${selectedInvId===i.id?'selected':''}>${i.id}</option>`).join('')}</select></div><div class="field"><label>Client</label><input id="rClient" value="${rec?.client||inv?.client||''}"></div><div class="field"><label>Date</label><input id="rDate" type="date" value="${rec?.date||Logic.today()}"></div><div class="field"><label>Method</label><select id="rMethod">${['Cash','Bank Transfer','OMT / Wish','Check','Other'].map(m=>`<option ${((rec?.method||'Cash')===m)?'selected':''}>${m}</option>`).join('')}</select></div><div class="field"><label>Currency</label><select id="rCurrency"><option ${(rec?.currency||inv?.currency||'USD')==='USD'?'selected':''}>USD</option><option ${(rec?.currency||inv?.currency)==='LBP'?'selected':''}>LBP</option></select></div><div class="field"><label>Exchange Rate LBP / USD</label><input id="rRate" type="number" value="${rate}"></div><div class="field"><label>Amount Paid $</label><input id="rAmount" type="number" value="${rec?rec.amount:(inv?inv.balance:0)}"></div><div class="field"><label>Notes</label><input id="rNotes" value="${rec?.notes||''}"></div></div><button class="btn green" onclick="App.saveReceipt('${receiptId||''}')">${receiptId?'Update Receipt':'Save Receipt'}</button>`); },
  saveReceipt(receiptId=''){ const amount=Number(rAmount.value||0); const rec={id:receiptId||Logic.docNo('RC',this.data.receipts),invoiceId:rInv.value,client:rClient.value,date:rDate.value,method:rMethod.value,currency:rCurrency.value,exchangeRate:Number(rRate.value||this.data.settings.exchangeRate||89500),amount,balance:0,notes:rNotes.value}; if(receiptId){ const idx=this.data.receipts.findIndex(r=>r.id===receiptId); if(idx>=0)this.data.receipts[idx]=rec; } else this.data.receipts.push(rec); this.recalcInvoicePayments(); const saved=this.data.receipts.find(r=>r.id===rec.id); this.save(); this.closeModal(); this.render(); this.toast(receiptId?'Receipt updated':'Receipt created and invoice updated'); },
  recalcInvoicePayments(){ this.data.invoices.forEach(inv=>{ inv.paid=this.data.receipts.filter(r=>r.invoiceId===inv.id).reduce((a,r)=>a+Number(r.amount||0),0); Logic.normalizeInvoice(inv); this.data.receipts.filter(r=>r.invoiceId===inv.id).forEach(r=>r.balance=inv.balance); }); },
  companyBlock(){ return `<div class="doc-company"><b>GM Security Systems</b><br>Ets. Georges E. Mazraani<br>Main Road<br>Bsalim, Mont-Liban 00961<br>Lebanon<br><br>+961 70 339779<br>info@gmsecuritysrv.com</div>`; },
  clientBlock(clientName){ const c=this.getClientByName(clientName)||{}; const name=this.clientDisplay(c)||clientName||''; return `<div class="doc-bill"><div class="doc-label">BILL TO</div><b>${name}</b><br>${c.accountNo?`Account: ${c.accountNo}<br>`:''}${c.location?`${c.location}<br>`:''}Lebanon<br><br>${c.phone||''}${c.email?`<br>${c.email}`:''}</div>`; },
  rateOf(d){ const c=this.getClientByName(d.client)||{}; return Number(d.exchangeRate||c.exchangeRate||this.data.settings.exchangeRate||89500); },
  lbpLine(amount, rate){ return Logic.lbp(Number(amount||0)*Number(rate||this.data.settings.exchangeRate||89500)); },
  viewDoc(type,id){ const list=type==='quote'?'quotes':type==='invoice'?'invoices':'receipts'; const d=this.data[list].find(x=>x.id===id); if(!d)return; this.modal(type.toUpperCase(),`<div class="print-area" id="printDoc">${this.printHtml(type,d)}</div><br><button class="btn primary" onclick="App.printDocument('${type}','${id}')">Print / PDF</button> <button class="btn ghost" onclick="App.copyText('${type}','${id}')">Copy WhatsApp Text</button>`); },
  printDocument(type,id){ const list=type==='quote'?'quotes':type==='invoice'?'invoices':'receipts'; const d=this.data[list].find(x=>x.id===id); if(!d)return; const html=this.printHtml(type,d); const w=window.open('','_blank'); if(!w){this.toast('Allow popups to print');return;} w.document.write(`<!doctype html><html><head><title>${d.id}</title><style>${this.printCss()}</style></head><body>${html}<script>window.onload=()=>{setTimeout(()=>window.print(),250)}<\/script></body></html>`); w.document.close(); },
  printCss(){ return `@page{size:A4;margin:0} body{margin:0;background:white;color:#111}.a4-doc{width:210mm;min-height:297mm;background:#fff;color:#111;margin:0 auto;padding:13mm 14mm;box-sizing:border-box;font-family:Arial,Helvetica,sans-serif;font-size:12.5px}.doc-top{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:22px}.doc-title-wrap{text-align:right}.doc-title{font-size:42px;letter-spacing:2px;font-weight:500;margin-bottom:20px}.doc-company{line-height:1.35;font-size:13px}.doc-info-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:24px;border-top:1px solid #ddd;border-bottom:1px solid #eee;padding:16px 0;margin-bottom:18px}.doc-label{font-size:12px;color:#888;letter-spacing:1px;margin-bottom:4px}.doc-bill{line-height:1.45}.doc-meta p{display:flex;justify-content:space-between;gap:16px;margin:4px 0}.doc-meta .grand{background:#f0f0f0;padding:6px 8px;font-size:14px}.doc-table{width:100%;border-collapse:collapse;margin-top:8px}.doc-table th{background:#3f3f3f;color:#fff;font-size:12px;text-align:left;padding:10px;border-bottom:0}.doc-table td{color:#111;padding:10px;border-bottom:1px solid #eee;vertical-align:top}.doc-table .num{text-align:right;white-space:nowrap}.part-col{width:120px;color:#555}.doc-summary{display:grid;grid-template-columns:1fr 330px;gap:20px;margin-top:18px;border-top:4px solid #eee;padding-top:14px}.doc-summary p{display:flex;justify-content:space-between;margin:7px 0}.doc-notes{margin-top:18px;line-height:1.5;border-top:1px solid #eee;padding-top:12px}.doc-footer{text-align:center;color:#888;margin-top:58mm}.receipt-box{border:1px solid #ddd;background:#fafafa;padding:16px;line-height:1.8;margin:20px 0}` },
  printHtml(type,d){
    const isQ=type==='quote', isI=type==='invoice', isR=type==='receipt';
    const rate=this.rateOf(d), total=Number(d.total||d.amount||0), paid=Number(d.paid||d.amount||0), balance=Number(d.balance||0);
    const title=isQ?'QUOTATION':isI?'INVOICE':'RECEIPT';
    const dateLabel=isQ?'Estimate Date':isI?'Invoice Date':'Receipt Date';
    const numberLabel=isQ?'Estimate Number':isI?'Invoice Number':'Receipt Number';
    const dueLabel=isQ?'Valid Until':isI?'Due Date':'Invoice Ref';
    const dueValue=isQ?(d.validUntil||''):isI?(d.due||''):(d.invoiceId||'Manual');
    const rows=(d.items||[]).map(i=>`<tr><td class="part-col">${i.partNo||''}</td><td>${i.description||''}</td><td class="num">${i.qty||''}</td><td class="num">${Logic.money(i.price||0)}</td><td class="num">${Logic.money(Number(i.qty||0)*Number(i.price||0))}</td></tr>`).join('');
    const receiptDetails=isR?`<div class="receipt-box"><b>Payment Method:</b> ${d.method||''}<br><b>Amount Paid:</b> ${Logic.money(d.amount||0)}<br><b>Remaining Balance:</b> ${Logic.money(d.balance||0)}</div>`:'';
    return `<div class="a4-doc"><div class="doc-top"><div></div><div class="doc-title-wrap"><div class="doc-title">${title}</div>${this.companyBlock()}</div></div><div class="doc-info-grid">${this.clientBlock(d.client)}<div class="doc-meta"><p><b>${numberLabel}:</b> ${d.id}</p><p><b>${dateLabel}:</b> ${d.date||''}</p><p><b>${dueLabel}:</b> ${dueValue}</p><p><b>Currency:</b> ${d.currency||'USD'}</p><p><b>Exchange Rate:</b> 1 USD = ${Number(rate).toLocaleString()} LBP</p><p class="grand"><b>Grand Total (USD):</b> ${Logic.money(total)}</p>${isI?`<p><b>Paid:</b> ${Logic.money(paid)}</p><p><b>Balance Due:</b> ${Logic.money(balance)}</p>`:''}</div></div>${rows?`<table class="doc-table"><thead><tr><th>Item #</th><th>Description</th><th>Quantity</th><th>Price</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table>`:receiptDetails}<div class="doc-summary"><div></div><div><p><b>Grand Total (USD):</b> ${Logic.money(total)}</p>${isR?`<p><b>Amount Paid:</b> ${Logic.money(d.amount||0)}</p><p><b>Remaining Balance:</b> ${Logic.money(d.balance||0)}</p>`:''}</div></div>${(d.notes||d.terms)?`<div class="doc-notes"><b>Notes:</b><br>${d.notes||d.terms}</div>`:''}<div class="doc-notes"><b>Terms & Conditions:</b><br>${isQ?'This quotation is valid until the date mentioned above. ':''}Prices are in USD unless otherwise stated. Exchange rate is shown for LBP reference.</div><div class="doc-footer">info@gmsecuritysrv.com</div></div>` },
  waItemLines(items){
    return (items||[]).map((i,idx)=>{
      const itemNo = i.partNo ? `${i.partNo} - ` : '';
      const desc = i.description || i.name || 'Item';
      const qty = Number(i.qty || 0);
      const price = Number(i.price || 0);
      const amount = qty * price;
      return `${idx+1}. ${itemNo}${desc}\n   Qty: ${qty} × ${Logic.money(price)} = ${Logic.money(amount)}`;
    }).join('\n');
  },
  buildWhatsAppText(type,d){
    const company = `GM Security Systems`;
    const line = `------------------------------`;
    const rate = Number(this.rateOf ? this.rateOf(d) : (this.data.settings.exchangeRate || 89500)).toLocaleString();
    if(type==='quote'){
      const subtotal = Logic.calcItems(d.items||[]);
      const discount = Logic.discountAmount(subtotal, d.discountType || 'amount', d.discountValue ?? d.discount ?? 0);
      const total = Number(d.total || Logic.calcDocTotal(d));
      const notes = d.notes ? `\nNotes:\n${d.notes}` : '';
      const terms = d.terms ? `\nTerms:\n${d.terms}` : '';
      return `${company}\nQUOTATION ${d.id}\n${line}\nClient: ${d.client || '-'}\nDate: ${d.date || '-'}\nValid Until: ${d.validUntil || '-'}\nStatus: ${d.status || 'Draft'}\nCurrency: USD\nExchange Rate: 1 USD = ${rate} LBP\n\nItems:\n${this.waItemLines(d.items)}\n\nSubtotal: ${Logic.money(subtotal)}${discount>0?`\nDiscount: -${Logic.money(discount)}`:''}\nGrand Total: ${Logic.money(total)}${notes}${terms}\n\nThank you,\nGM Security Systems`;
    }
    if(type==='invoice'){
      const inv = Logic.normalizeInvoice({...d});
      const subtotal = Logic.calcItems(inv.items||[]);
      const discount = Logic.discountAmount(subtotal, inv.discountType || 'amount', inv.discountValue ?? inv.discount ?? 0);
      const notes = inv.notes ? `\nNotes:\n${inv.notes}` : '';
      return `${company}\nINVOICE ${inv.id}\n${line}\nClient: ${inv.client || '-'}\nDate: ${inv.date || '-'}\nDue Date: ${inv.due || '-'}\nStatus: ${inv.status}\nCurrency: USD\nExchange Rate: 1 USD = ${rate} LBP\n\nItems:\n${this.waItemLines(inv.items)}\n\nSubtotal: ${Logic.money(subtotal)}${discount>0?`\nDiscount: -${Logic.money(discount)}`:''}\nGrand Total: ${Logic.money(inv.total)}\nPaid: ${Logic.money(inv.paid || 0)}\nBalance Due: ${Logic.money(inv.balance || 0)}${notes}\n\nThank you,\nGM Security Systems`;
    }
    const receiptNotes = d.notes ? `\nNotes:\n${d.notes}` : '';
    return `${company}\nRECEIPT ${d.id}\n${line}\nClient: ${d.client || '-'}\nDate: ${d.date || '-'}\nInvoice Ref: ${d.invoiceId || 'Manual'}\nPayment Method: ${d.method || '-'}\nCurrency: USD\nExchange Rate: 1 USD = ${rate} LBP\n\nAmount Paid: ${Logic.money(d.amount || 0)}\nRemaining Balance: ${Logic.money(d.balance || 0)}${receiptNotes}\n\nThank you,\nGM Security Systems`;
  },
  copyToClipboard(txt){
    if(navigator.clipboard && window.isSecureContext){
      navigator.clipboard.writeText(txt).catch(()=>this.copyFallback(txt));
    } else this.copyFallback(txt);
  },
  copyFallback(txt){
    const ta=document.createElement('textarea'); ta.value=txt; ta.style.position='fixed'; ta.style.left='-9999px'; document.body.appendChild(ta); ta.focus(); ta.select(); try{document.execCommand('copy')}catch(e){} document.body.removeChild(ta);
  },
  copyText(type,id){ const list=type==='quote'?'quotes':type==='invoice'?'invoices':'receipts'; const d=this.data[list].find(x=>x.id===id); if(!d)return; const txt=this.buildWhatsAppText(type,d); this.copyToClipboard(txt); this.toast('Detailed WhatsApp text copied'); },
  statementById(id){ const c=this.data.clients.find(x=>x.id===id); if(!c){this.toast('Client not found');return;} this.statement(this.clientDisplay(c)); },
  statement(client){
    const c=this.getClientByName(client)||{}; const rate=Number(c.exchangeRate||this.data.settings.exchangeRate||89500);
    const inv=this.data.invoices.map(Logic.normalizeInvoice).filter(i=>i.client===client), rec=this.data.receipts.filter(r=>r.client===client);
    const total=inv.reduce((a,i)=>a+Number(i.total||0),0), paid=rec.reduce((a,r)=>a+Number(r.amount||0),0), bal=Math.max(0,total-paid);
    const invRows=inv.map(i=>`<tr><td>${i.id}</td><td>${i.date}</td><td>${i.due||''}</td><td>${i.status}</td><td class="num">${Logic.money(i.total)}</td><td class="num">${Logic.money(i.balance)}</td></tr>`).join('');
    const recRows=rec.map(r=>`<tr><td>${r.id}</td><td>${r.date}</td><td>${r.invoiceId||'Manual'}</td><td>${r.method||''}</td><td class="num">${Logic.money(r.amount)}</td></tr>`).join('');
    this.modal('Statement of Account',`<div class="print-area"><div class="a4-doc"><div class="doc-top"><div></div><div class="doc-title-wrap"><div class="doc-title">STATEMENT</div>${this.companyBlock()}</div></div><div class="doc-info-grid">${this.clientBlock(client)}<div class="doc-meta"><p><b>Statement Date:</b> ${Logic.today()}</p><p><b>Currency:</b> ${c.currency||'USD'}</p><p><b>Exchange Rate:</b> 1 USD = ${rate.toLocaleString()} LBP</p><p class="grand"><b>Balance Due:</b> ${Logic.money(bal)}</p></div></div><div class="doc-summary"><div></div><div><p><b>Total Invoiced:</b> ${Logic.money(total)}</p><p><b>Total Paid:</b> ${Logic.money(paid)}</p><p><b>Balance Due:</b> ${Logic.money(bal)}</p></div></div><h3>Invoices</h3><table class="doc-table"><thead><tr><th>Invoice</th><th>Date</th><th>Due</th><th>Status</th><th>Total</th><th>Balance</th></tr></thead><tbody>${invRows}</tbody></table><h3>Receipts</h3><table class="doc-table"><thead><tr><th>Receipt</th><th>Date</th><th>Invoice</th><th>Method</th><th>Paid USD</th></tr></thead><tbody>${recRows}</tbody></table><div class="doc-footer">info@gmsecuritysrv.com</div></div></div><br><button class="btn primary" onclick="App.printRawHtml('Statement', document.querySelector('.modal-body .print-area').innerHTML)">Print Statement</button>`); },
  edit(type,id){ if(type==='quote')this.openDocForm('quote',id); if(type==='invoice')this.openDocForm('invoice',id); if(type==='receipt')this.openReceiptForm('',id); },
  del(type,id){
    const map={quote:'quotes',invoice:'invoices',receipt:'receipts',client:'clients',supplier:'suppliers',visit:'visits',inventory:'inventory'};
    if(!map[type])return;
    if(type==='inventory'){
      const it=this.data.inventory.find(x=>x.id===id); if(!it)return;
      const used=this.data.quotes.some(q=>(q.items||[]).some(li=>li.partNo===it.partNo))||this.data.invoices.some(inv=>(inv.items||[]).some(li=>li.partNo===it.partNo));
      const msg=used ? `Delete item "${it.partNo||it.description}" from Inventory? Existing invoices/quotations will remain for history.` : `Delete item "${it.partNo||it.description}"?`;
      if(!confirm(msg))return;
    } else if(type==='client'){
      const c=this.data.clients.find(x=>x.id===id); if(!c)return;
      const name=this.clientDisplay(c);
      const hasDocs=this.data.quotes.some(q=>q.client===name)||this.data.invoices.some(i=>i.client===name)||this.data.receipts.some(r=>r.client===name);
      const msg=hasDocs ? `Delete client "${name}" from Clients list? Existing quotations, invoices and receipts will remain for history.` : `Delete client "${name}"?`;
      if(!confirm(msg))return;
    } else if(!confirm('Delete?'))return;
    this.data[map[type]]=this.data[map[type]].filter(x=>x.id!==id);
    if(type==='receipt')this.recalcInvoicePayments();
    this.save(); this.render();
    this.toast(type==='receipt'?'Receipt deleted and invoice balance updated':type==='client'?'Client deleted':type==='inventory'?'Inventory item deleted':'Deleted');
  },
  openSettings(){this.go('settings')},
  exportBackup(){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(this.data,null,2)],{type:'application/json'})); a.download='gm-security-backup-'+Logic.today()+'.json'; a.click(); },
  importBackup(e){ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{this.data=JSON.parse(r.result);this.save();this.render();this.toast('Backup imported')}; r.readAsText(f); },
  printRawHtml(title,html){ const w=window.open('','_blank'); if(!w){this.toast('Allow popups to print');return;} w.document.write(`<!doctype html><html><head><title>${title}</title><style>${this.printCss()}</style></head><body>${html}<script>window.onload=()=>{setTimeout(()=>window.print(),250)}<\/script></body></html>`); w.document.close(); },
  resetDemo(){ if(confirm('Reset all demo data?')){localStorage.removeItem('gm_data_v5');this.load();this.render();} }
};
if(typeof document!=='undefined') document.addEventListener('DOMContentLoaded',()=>App.init());
if(typeof module!=='undefined') module.exports={Logic,App};
