/* GM Security Systems - Static Pro Demo */
const Logic = (() => {
  const money = n => '$' + Number(n || 0).toLocaleString();
  const today = () => new Date().toISOString().slice(0,10);
  const uid = p => p + '-' + Math.random().toString(36).slice(2,7).toUpperCase();
  const docNo = (prefix, list) => prefix + '-' + String((list?.length || 0) + 1).padStart(4,'0');
  const calcItems = items => (items || []).reduce((a,i)=>a + Number(i.qty||0)*Number(i.price||0),0);
  const blobText = obj => JSON.stringify(obj).toLowerCase();
  const deepSearch = (obj, q) => !q || blobText(obj).includes(String(q).toLowerCase());
  const invoiceStatus = inv => Number(inv.balance||0) <= 0 ? 'Paid' : Number(inv.paid||0) > 0 ? 'Partial' : (inv.due && inv.due < today() ? 'Overdue' : 'Unpaid');
  function defaultData(){
    return {
      settings:{user:'admin', pass:'gm1234', autoLock:30, lighter:true},
      clients:[
        {id:uid('CL'),name:'ABC Trading Co.',phone:'+961 70 123456',email:'info@abc.com',location:'Beirut',status:'Active',notes:''},
        {id:uid('CL'),name:'Green Valley Hotel',phone:'+961 71 654321',email:'gvh@hotel.com',location:'Jounieh',status:'Active',notes:''},
        {id:uid('CL'),name:'City Mall',phone:'+961 76 999888',email:'city@mall.com',location:'Sin El Fil',status:'Active',notes:''}
      ],
      inventory:[
        {id:uid('IT'),name:'IP Camera 4MP',category:'CCTV',unit:'pcs',qty:14,min:5,cost:110,price:180,supplier:''},
        {id:uid('IT'),name:'DVR 8CH',category:'CCTV',unit:'pcs',qty:3,min:2,cost:280,price:420,supplier:''},
        {id:uid('IT'),name:'Installation & Configuration',category:'Service',unit:'job',qty:999,min:0,cost:0,price:150,supplier:''},
        {id:uid('IT'),name:'CAT6 Cable',category:'Network',unit:'rolls',qty:8,min:3,cost:30,price:45,supplier:''}
      ],
      suppliers:[{id:uid('SU'),name:'TechLine Lebanon',contact:'Ali Hassan',phone:'+961 70 777111',category:'CCTV & Alarm',balance:2400,status:'Active'}],
      quotes:[
        {id:'QT-0001',clientId:'',client:'City Mall',date:'2026-06-29',validUntil:'2026-07-06',status:'Pending',items:[{description:'IP Camera 4MP',qty:10,price:180},{description:'Installation & Configuration',qty:1,price:550}],discount:0,notes:'',terms:'50% down payment, balance upon installation.',total:2350},
        {id:'QT-0002',clientId:'',client:'Green Valley Hotel',date:'2026-06-29',validUntil:'2026-07-06',status:'Draft',items:[{description:'WiFi AP Indoor',qty:4,price:150},{description:'Cabling & Setup',qty:1,price:300}],discount:0,notes:'',terms:'Valid for 7 days.',total:900}
      ],
      invoices:[
        {id:'INV-0001',clientId:'',client:'ABC Trading Co.',date:'2026-06-25',due:'2026-07-25',status:'Unpaid',items:[{description:'CCTV Maintenance Visit',qty:1,price:850}],discount:0,total:850,paid:0,balance:850,notes:''},
        {id:'INV-0002',clientId:'',client:'Green Valley Hotel',date:'2026-06-20',due:'2026-07-20',status:'Paid',items:[{description:'WiFi AP Indoor',qty:4,price:350},{description:'Cabling & Setup',qty:1,price:1000}],discount:0,total:2400,paid:2400,balance:0,notes:''}
      ],
      receipts:[{id:'RC-0001',invoiceId:'INV-0002',client:'Green Valley Hotel',date:'2026-06-21',method:'Cash',amount:2400,balance:0,notes:'Full payment received.'}],
      visits:[{id:uid('V'),client:'ABC Trading Co.',type:'CCTV Maintenance',date:'2026-06-30',time:'10:00',status:'Scheduled',notes:''}]
    }
  }
  function normalizeInvoice(inv){ inv.total = calcItems(inv.items) - Number(inv.discount||0); inv.balance = Math.max(0, Number(inv.total||0) - Number(inv.paid||0)); inv.status = invoiceStatus(inv); return inv; }
  return {money,today,uid,docNo,calcItems,deepSearch,defaultData,normalizeInvoice};
})();

const App = {
  data:null,page:'dashboard',editing:null,sessionTimer:null,lastActivity:Date.now(),
  pages:{dashboard:['Dashboard','Business overview and quick actions'],quotations:['Quotations','Create, search, print and convert quotes'],invoices:['Invoices','Billing, receipts and payment tracking'],receipts:['Receipts','Payments and reprints'],clients:['Clients','Client accounts and statements'],suppliers:['Suppliers','Vendors and balances'],inventory:['Inventory','Items, services and stock'],visits:['Visits','Scheduling and field work'],reports:['Reports','Profit, loss and balances'],settings:['Settings','Security and backup']},
  nav:[['Main'],['dashboard','⊞','Dashboard'],['Sales'],['quotations','📋','Quotations'],['invoices','🧾','Invoices'],['receipts','💵','Receipts'],['Operations'],['clients','👥','Clients'],['suppliers','🏭','Suppliers'],['visits','📅','Visits'],['inventory','📦','Inventory'],['Finance'],['reports','📊','Reports'],['settings','⚙','Settings']],
  init(){ this.load(); this.bindLogin(); this.renderNav(); if(localStorage.getItem('gm_session')==='1') this.unlock(); else this.lock(); },
  load(){ try{this.data=JSON.parse(localStorage.getItem('gm_data_v4'))||Logic.defaultData()}catch(e){this.data=Logic.defaultData()} this.save(); },
  save(){ localStorage.setItem('gm_data_v4',JSON.stringify(this.data)); },
  bindLogin(){
    const ok=()=>this.tryLogin(); document.getElementById('loginBtn').onclick=ok; document.getElementById('loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')ok()}); document.getElementById('logoutBtn').onclick=()=>this.lock(true);
    ['click','keydown','touchstart'].forEach(ev=>document.addEventListener(ev,()=>this.lastActivity=Date.now())); setInterval(()=>this.checkAutoLock(),30000);
  },
  tryLogin(){ const u=loginUser.value.trim(), p=loginPass.value; if(u===this.data.settings.user && p===this.data.settings.pass){localStorage.setItem('gm_session','1'); loginError.textContent=''; loginPass.value=''; this.unlock()} else loginError.textContent='Wrong username or password'; },
  unlock(){ loginScreen.classList.add('hidden'); app.classList.remove('hidden'); this.lastActivity=Date.now(); this.render(); },
  lock(manual=false){ localStorage.removeItem('gm_session'); app.classList.add('hidden'); loginScreen.classList.remove('hidden'); if(manual) this.toast('Logged out'); },
  checkAutoLock(){ if(localStorage.getItem('gm_session')!=='1')return; const min=Number(this.data.settings.autoLock||30); if(Date.now()-this.lastActivity > min*60000) this.lock(true); },
  toast(t){ const el=document.getElementById('toast'); el.textContent=t; el.style.display='block'; clearTimeout(this._toast); this._toast=setTimeout(()=>el.style.display='none',2600); },
  renderNav(){ const build=(target,bottom=false)=>{target.innerHTML=this.nav.map(n=>n.length===1&&!bottom?`<div class="nav-section">${n[0]}</div>`:n.length===1?'':`<div class="nav-item ${this.page===n[0]?'active':''}" onclick="App.go('${n[0]}')"><span>${n[1]}</span><span>${n[2]}</span></div>`).join('')}; build(nav); build(bottomNav,true); },
  go(p){ this.page=p; this.renderNav(); this.render(); },
  render(){ const [t,s]=this.pages[this.page]; pageTitle.textContent=t; pageSub.textContent=s; const map={dashboard:this.dashboard,quotations:this.quotations,invoices:this.invoices,receipts:this.receipts,clients:this.clients,suppliers:this.suppliers,inventory:this.inventory,visits:this.visits,reports:this.reports,settings:this.settings}; view.innerHTML=map[this.page].call(this); },
  rowActions(type,id){ return `<div class="row-actions"><button class="btn ghost mini" onclick="App.viewDoc('${type}','${id}')">View</button><button class="btn ghost mini" onclick="App.edit('${type}','${id}')">Edit</button><button class="btn danger mini" onclick="App.del('${type}','${id}')">Delete</button></div>` },
  dashboard(){ const d=this.data, inv=d.invoices.map(Logic.normalizeInvoice); const revenue=inv.reduce((a,i)=>a+Number(i.paid||0),0), invoiced=inv.reduce((a,i)=>a+Number(i.total||0),0), outstanding=inv.reduce((a,i)=>a+Number(i.balance||0),0); const estCost=d.inventory.reduce((a,i)=>a+Number(i.cost||0)*Math.min(Number(i.qty||0),1),0); const profit=revenue-estCost; const lastQ=[...d.quotes].slice(-5).reverse(), lastI=[...inv].slice(-5).reverse(); const byClient={}; inv.forEach(i=>byClient[i.client]=(byClient[i.client]||0)+Number(i.total||0)); const top=Object.entries(byClient).sort((a,b)=>b[1]-a[1])[0];
    return `<div class="quick-grid"><button class="btn primary" onclick="App.openDocForm('invoice')">+ New Invoice</button><button class="btn primary" onclick="App.openDocForm('quote')">+ New Quotation</button><button class="btn" onclick="App.openClientForm()">+ New Client</button><button class="btn green" onclick="App.openReceiptForm()">+ New Receipt</button></div>
    <div class="circles card"><div class="circle"><div><strong>${Logic.money(revenue)}</strong><span>Collected</span></div></div><div class="circle"><div><strong>${Logic.money(invoiced)}</strong><span>Total Invoiced</span></div></div><div class="circle"><div><strong>${Logic.money(profit)}</strong><span>Net Profit</span></div></div><div class="circle"><div><strong>${Logic.money(outstanding)}</strong><span>Outstanding</span></div></div></div>
    <div class="grid stats" style="margin-top:16px"><div class="stat-card"><div class="bar"></div><div class="stat-num">${d.quotes.filter(q=>q.status==='Pending'||q.status==='Sent').length}</div><div class="stat-label">Pending Quotes</div></div><div class="stat-card"><div class="bar"></div><div class="stat-num">${inv.filter(i=>i.status==='Overdue').length}</div><div class="stat-label">Overdue Invoices</div></div><div class="stat-card"><div class="bar"></div><div class="stat-num">${top?top[0]:'—'}</div><div class="stat-label">Top Selling Client</div></div><div class="stat-card"><div class="bar"></div><div class="stat-num">${d.inventory.filter(i=>Number(i.qty)<=Number(i.min)).length}</div><div class="stat-label">Low Stock</div></div></div>
    <div class="grid two" style="margin-top:16px"><div class="card"><h3 class="section-title">Last 5 Quotations</h3>${lastQ.map(q=>this.listRow(q.id,q.client,Logic.money(q.total),q.status)).join('')||'No quotations'}</div><div class="card"><h3 class="section-title">Last 5 Invoices</h3>${lastI.map(i=>this.listRow(i.id,i.client,Logic.money(i.total),i.status)).join('')||'No invoices'}</div></div>`},
  listRow(a,b,c,status){return `<div class="list-row"><div><b>${a}</b><div class="muted small">${b}</div></div><div class="right"><b>${c}</b><br><span class="badge ${status}">${status}</span></div></div>`},
  searchToolbar(type,btn){ return `<div class="toolbar"><input class="search" id="search_${type}" placeholder="Search by client, number, item, amount, notes..." oninput="App.renderList('${type}')"><div>${btn||''}</div></div><div id="list_${type}"></div>`},
  quotations(){ setTimeout(()=>this.renderList('quotes'),0); return this.searchToolbar('quotes',`<button class="btn primary" onclick="App.openDocForm('quote')">+ New Quotation</button>`) },
  invoices(){ setTimeout(()=>this.renderList('invoices'),0); return this.searchToolbar('invoices',`<button class="btn primary" onclick="App.openDocForm('invoice')">+ New Invoice</button>`) },
  receipts(){ setTimeout(()=>this.renderList('receipts'),0); return this.searchToolbar('receipts',`<button class="btn green" onclick="App.openReceiptForm()">+ New Receipt</button>`) },
  clients(){ setTimeout(()=>this.renderList('clients'),0); return this.searchToolbar('clients',`<button class="btn primary" onclick="App.openClientForm()">+ New Client</button>`) },
  suppliers(){ setTimeout(()=>this.renderList('suppliers'),0); return this.searchToolbar('suppliers',`<button class="btn primary" onclick="App.openSupplierForm()">+ Supplier</button>`) },
  inventory(){ setTimeout(()=>this.renderList('inventory'),0); return this.searchToolbar('inventory',`<button class="btn primary" onclick="App.openItemForm()">+ Item / Service</button>`) },
  visits(){ setTimeout(()=>this.renderList('visits'),0); return this.searchToolbar('visits',`<button class="btn primary" onclick="App.openVisitForm()">+ Schedule Visit</button>`) },
  reports(){ return `<div class="grid two"><div class="card"><h3 class="section-title">Profit & Loss</h3>${this.dashboard().match(/<div class="circles card">[\s\S]*?<\/div><\/div><\/div><\/div><\/div>/)?.[0]||''}</div><div class="card"><h3 class="section-title">Outstanding Balances</h3>${this.data.invoices.map(Logic.normalizeInvoice).filter(i=>i.balance>0).map(i=>this.listRow(i.id,i.client,Logic.money(i.balance),i.status)).join('')||'Clear'}</div></div>`},
  settings(){ return `<div class="card"><h3 class="section-title">Security</h3><div class="form-grid"><div class="field"><label>Username</label><input id="setUser" value="${this.data.settings.user}"></div><div class="field"><label>Password</label><input id="setPass" value="${this.data.settings.pass}"></div><div class="field"><label>Auto lock minutes</label><input id="setLock" type="number" value="${this.data.settings.autoLock||30}"></div></div><button class="btn primary" onclick="App.saveSettings()">Save Security</button></div><div class="card"><h3 class="section-title">Backup</h3><button class="btn ghost" onclick="App.exportBackup()">Export Backup JSON</button> <label class="btn ghost">Import Backup <input type="file" hidden onchange="App.importBackup(event)"></label> <button class="btn danger" onclick="App.resetDemo()">Reset Demo Data</button></div>`},
  saveSettings(){ this.data.settings.user=setUser.value.trim()||'admin'; this.data.settings.pass=setPass.value||'gm1234'; this.data.settings.autoLock=Number(setLock.value||30); this.save(); this.toast('Security settings saved') },
  renderList(type){ const q=document.getElementById('search_'+type)?.value||''; let rows=this.data[type].filter(x=>Logic.deepSearch(x,q)); const el=document.getElementById('list_'+type); if(!el)return; if(type==='quotes') el.innerHTML=this.table(['Quote #','Client','Date','Amount','Status',''],rows.map(x=>[x.id,x.client,x.date,Logic.money(x.total),`<span class="badge ${x.status}">${x.status}</span>`,this.rowActions('quote',x.id)+`<button class="btn green mini" onclick="App.convertQuote('${x.id}')">→ Invoice</button>`]));
    if(type==='invoices') el.innerHTML=this.table(['Invoice #','Client','Due','Total','Paid','Balance','Status',''],rows.map(x=>{x=Logic.normalizeInvoice(x); return [x.id,x.client,x.due,Logic.money(x.total),Logic.money(x.paid),Logic.money(x.balance),`<span class="badge ${x.status}">${x.status}</span>`,this.rowActions('invoice',x.id)+`<button class="btn green mini" onclick="App.openReceiptForm('${x.id}')">Receipt</button>`]}));
    if(type==='receipts') el.innerHTML=this.table(['Receipt #','Client','Invoice','Date','Method','Amount',''],rows.map(x=>[x.id,x.client,x.invoiceId,x.date,x.method,Logic.money(x.amount),`<div class="row-actions"><button class="btn ghost mini" onclick="App.viewDoc('receipt','${x.id}')">View/Print</button></div>`]));
    if(type==='clients') el.innerHTML=this.table(['Client','Phone','Location','Balance','Status',''],rows.map(c=>[c.name,c.phone,c.location,Logic.money(this.clientBalance(c.name)),`<span class="badge ${c.status}">${c.status}</span>`,`<div class="row-actions"><button class="btn ghost mini" onclick="App.statement('${c.name}')">Statement</button><button class="btn ghost mini" onclick="App.openClientForm('${c.id}')">Edit</button></div>`]));
    if(type==='inventory') el.innerHTML=this.table(['Item / Service','Category','Stock','Min','Cost','Sell','Status',''],rows.map(i=>[i.name,i.category,`${i.qty} ${i.unit}`,i.min,Logic.money(i.cost),Logic.money(i.price),`<span class="badge ${Number(i.qty)<=Number(i.min)?'Low':'OK'}">${Number(i.qty)<=Number(i.min)?'Low':'OK'}</span>`,`<button class="btn ghost mini" onclick="App.openItemForm('${i.id}')">Edit</button>`]));
    if(type==='suppliers') el.innerHTML=this.table(['Supplier','Contact','Phone','Category','Balance','Status',''],rows.map(s=>[s.name,s.contact,s.phone,s.category,Logic.money(s.balance),`<span class="badge ${s.status}">${s.status}</span>`,`<button class="btn ghost mini" onclick="App.openSupplierForm('${s.id}')">Edit</button>`]));
    if(type==='visits') el.innerHTML=this.table(['Client','Type','Date','Time','Status','Notes'],rows.map(v=>[v.client,v.type,v.date,v.time,`<span class="badge ${v.status}">${v.status}</span>`,v.notes||'']));
  },
  table(head,rows){ return `<div class="card table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>` },
  clientBalance(name){ return this.data.invoices.map(Logic.normalizeInvoice).filter(i=>i.client===name).reduce((a,i)=>a+Number(i.balance||0),0) },
  modal(title,body){ modalRoot.innerHTML=`<div class="modal-back" onclick="App.closeModal(event)"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h3>${title}</h3><button class="btn ghost" onclick="App.closeModal()">✕</button></div><div class="modal-body">${body}</div></div></div>` },
  closeModal(e){ if(e&&e.target.className!=='modal-back')return; modalRoot.innerHTML=''; },
  clientOptions(sel=''){return this.data.clients.map(c=>`<option value="${c.name}" ${sel===c.name?'selected':''}>${c.name}</option>`).join('')},
  itemOptions(){return this.data.inventory.map(i=>`<option value="${i.name}" data-price="${i.price}">${i.name}</option>`).join('')},
  openDocForm(kind,id){ const isQ=kind==='quote', list=isQ?'quotes':'invoices'; const old=id?this.data[list].find(x=>x.id===id):null; const doc=old||{id:Logic.docNo(isQ?'QT':'INV',this.data[list]),client:'',date:Logic.today(),due:Logic.today(),validUntil:Logic.today(),status:isQ?'Draft':'Unpaid',items:[{description:'',qty:1,price:0}],discount:0,paid:0,notes:'',terms:'Valid for 7 days.'};
    this.editing={kind,id:doc.id}; this.modal(isQ?'Quotation':'Invoice',`<div class="form-grid three"><div class="field"><label>Number</label><input id="docId" value="${doc.id}"></div><div class="field"><label>Client</label><select id="docClient"><option value="">Select client</option>${this.clientOptions(doc.client)}</select></div><div class="field"><label>Quick Client</label><button class="btn" onclick="App.quickClient()">+ Add Client Here</button></div><div class="field"><label>Date</label><input id="docDate" type="date" value="${doc.date}"></div><div class="field"><label>${isQ?'Valid Until':'Due Date'}</label><input id="docDue" type="date" value="${isQ?doc.validUntil:doc.due}"></div><div class="field"><label>Status</label><select id="docStatus">${(isQ?['Draft','Sent','Pending','Accepted','Rejected','Converted']:['Unpaid','Partial','Paid','Overdue']).map(s=>`<option ${doc.status===s?'selected':''}>${s}</option>`).join('')}</select></div></div><div class="items-box" id="itemsBox"></div><button class="btn ghost" onclick="App.addLine()">+ Add Line</button> <button class="btn" onclick="App.quickItem()">+ Add Item/Service Here</button><div class="totals"><div><span>Discount</span><input id="docDiscount" type="number" value="${doc.discount||0}" oninput="App.recalcForm()" style="width:110px"></div>${!isQ?`<div><span>Paid</span><input id="docPaid" type="number" value="${doc.paid||0}" oninput="App.recalcForm()" style="width:110px"></div>`:''}<div><span>Total</span><b id="docTotal">$0</b></div></div><div class="field"><label>Notes / Terms</label><textarea id="docNotes">${doc.notes||doc.terms||''}</textarea></div><button class="btn primary" onclick="App.saveDoc('${kind}')">Save ${isQ?'Quotation':'Invoice'}</button>`); this.formItems=JSON.parse(JSON.stringify(doc.items)); this.drawLines(); },
  drawLines(){ itemsBox.innerHTML=this.formItems.map((it,i)=>`<div class="item-line"><div class="field"><label>Description</label><input list="itemList" value="${it.description||''}" oninput="App.formItems[${i}].description=this.value; App.autofillPrice(${i},this.value)"></div><div class="field"><label>Qty</label><input type="number" value="${it.qty||1}" oninput="App.formItems[${i}].qty=this.value;App.recalcForm()"></div><div class="field"><label>Unit Price</label><input type="number" value="${it.price||0}" oninput="App.formItems[${i}].price=this.value;App.recalcForm()"></div><div class="field"><label>Total</label><input disabled value="${Logic.money(Number(it.qty||0)*Number(it.price||0))}"></div><button class="btn danger mini" onclick="App.formItems.splice(${i},1);App.drawLines()">✕</button></div>`).join('')+`<datalist id="itemList">${this.itemOptions()}</datalist>`; this.recalcForm(); },
  autofillPrice(i,val){ const item=this.data.inventory.find(x=>x.name.toLowerCase()===String(val).toLowerCase()); if(item){this.formItems[i].price=item.price; this.drawLines()} else this.recalcForm(); },
  addLine(){this.formItems.push({description:'',qty:1,price:0});this.drawLines()},
  recalcForm(){ const total=Logic.calcItems(this.formItems)-Number(document.getElementById('docDiscount')?.value||0); const el=document.getElementById('docTotal'); if(el)el.textContent=Logic.money(total); },
  quickClient(){ const name=prompt('New client name'); if(!name)return; const phone=prompt('Phone (optional)')||''; const location=prompt('Location (optional)')||''; const c={id:Logic.uid('CL'),name,phone,location,email:'',status:'Active',notes:''}; this.data.clients.push(c); this.save(); const sel=document.getElementById('docClient'); sel.innerHTML=`<option value="">Select client</option>${this.clientOptions(name)}`; sel.value=name; this.toast('Client saved to Clients') },
  quickItem(){ const name=prompt('Item / service description'); if(!name)return; const price=Number(prompt('Selling price')||0); const category=prompt('Category', 'Service')||'Service'; const item={id:Logic.uid('IT'),name,category,unit:'pcs',qty:0,min:0,cost:0,price,supplier:''}; this.data.inventory.push(item); this.save(); this.formItems.push({description:name,qty:1,price}); this.drawLines(); this.toast('Item saved to Inventory') },
  saveDoc(kind){ const isQ=kind==='quote', list=isQ?'quotes':'invoices'; let doc={id:docId.value.trim(),client:docClient.value,date:docDate.value,status:docStatus.value,items:this.formItems,discount:Number(docDiscount.value||0),notes:docNotes.value}; if(isQ){doc.validUntil=docDue.value; doc.terms=docNotes.value; doc.total=Logic.calcItems(doc.items)-doc.discount}else{doc.due=docDue.value; doc.paid=Number(docPaid.value||0); Logic.normalizeInvoice(doc)} const idx=this.data[list].findIndex(x=>x.id===this.editing.id); if(idx>=0)this.data[list][idx]=doc; else this.data[list].push(doc); this.save(); this.closeModal(); this.render(); this.toast((isQ?'Quotation':'Invoice')+' saved'); },
  openClientForm(id){ const c=id?this.data.clients.find(x=>x.id===id):{id:Logic.uid('CL'),name:'',phone:'',email:'',location:'',status:'Active',notes:''}; this.modal('Client',`<div class="form-grid"><div class="field"><label>Name</label><input id="cName" value="${c.name}"></div><div class="field"><label>Phone</label><input id="cPhone" value="${c.phone}"></div><div class="field"><label>Email</label><input id="cEmail" value="${c.email}"></div><div class="field"><label>Location</label><input id="cLoc" value="${c.location}"></div></div><button class="btn primary" onclick="App.saveClient('${c.id}')">Save Client</button>`); },
  saveClient(id){ const c={id,name:cName.value,phone:cPhone.value,email:cEmail.value,location:cLoc.value,status:'Active',notes:''}; const i=this.data.clients.findIndex(x=>x.id===id); if(i>=0)this.data.clients[i]=c; else this.data.clients.push(c); this.save(); this.closeModal(); this.render(); },
  openItemForm(id){ const it=id?this.data.inventory.find(x=>x.id===id):{id:Logic.uid('IT'),name:'',category:'Service',unit:'pcs',qty:0,min:0,cost:0,price:0,supplier:''}; this.modal('Item / Service',`<div class="form-grid three"><div class="field"><label>Name</label><input id="iName" value="${it.name}"></div><div class="field"><label>Category</label><input id="iCat" value="${it.category}"></div><div class="field"><label>Unit</label><input id="iUnit" value="${it.unit}"></div><div class="field"><label>Qty</label><input id="iQty" type="number" value="${it.qty}"></div><div class="field"><label>Cost</label><input id="iCost" type="number" value="${it.cost}"></div><div class="field"><label>Sell</label><input id="iPrice" type="number" value="${it.price}"></div></div><button class="btn primary" onclick="App.saveItem('${it.id}')">Save Item</button>`); },
  saveItem(id){ const it={id,name:iName.value,category:iCat.value,unit:iUnit.value,qty:Number(iQty.value),min:0,cost:Number(iCost.value),price:Number(iPrice.value),supplier:''}; const i=this.data.inventory.findIndex(x=>x.id===id); if(i>=0)this.data.inventory[i]=it; else this.data.inventory.push(it); this.save(); this.closeModal(); this.render(); },
  openSupplierForm(){ this.toast('Supplier form ready in next refinement'); }, openVisitForm(){ this.toast('Visit form ready in next refinement'); },
  convertQuote(id){ const q=this.data.quotes.find(x=>x.id===id); if(!q)return; const inv=Logic.normalizeInvoice({id:Logic.docNo('INV',this.data.invoices),client:q.client,date:Logic.today(),due:Logic.today(),items:q.items,discount:q.discount,total:q.total,paid:0,balance:q.total,status:'Unpaid',notes:'Converted from '+q.id}); this.data.invoices.push(inv); q.status='Converted'; this.save(); this.render(); this.toast('Converted to invoice'); },
  openReceiptForm(invoiceId=''){ const inv=this.data.invoices.find(i=>i.id===invoiceId); this.modal('Receipt',`<div class="form-grid"><div class="field"><label>Invoice</label><select id="rInv"><option value="">Manual</option>${this.data.invoices.map(i=>`<option ${invoiceId===i.id?'selected':''}>${i.id}</option>`).join('')}</select></div><div class="field"><label>Client</label><input id="rClient" value="${inv?inv.client:''}"></div><div class="field"><label>Date</label><input id="rDate" type="date" value="${Logic.today()}"></div><div class="field"><label>Method</label><select id="rMethod"><option>Cash</option><option>Bank Transfer</option><option>OMT / Wish</option><option>Check</option><option>Other</option></select></div><div class="field"><label>Amount</label><input id="rAmount" type="number" value="${inv?inv.balance:0}"></div><div class="field"><label>Notes</label><input id="rNotes" value=""></div></div><button class="btn green" onclick="App.saveReceipt()">Save Receipt</button>`); },
  saveReceipt(){ const id=Logic.docNo('RC',this.data.receipts); const inv=this.data.invoices.find(i=>i.id===rInv.value); const amount=Number(rAmount.value||0); let bal=0; if(inv){inv.paid=Number(inv.paid||0)+amount; Logic.normalizeInvoice(inv); bal=inv.balance} const rec={id,invoiceId:rInv.value,client:rClient.value||inv?.client||'',date:rDate.value,method:rMethod.value,amount,balance:bal,notes:rNotes.value}; this.data.receipts.push(rec); this.save(); this.closeModal(); this.render(); this.toast('Receipt created and invoice updated'); },
  viewDoc(type,id){ const list=type==='quote'?'quotes':type==='invoice'?'invoices':'receipts'; const d=this.data[list].find(x=>x.id===id); if(!d)return; this.modal(type.toUpperCase(),`<div class="print-area" id="printDoc">${this.printHtml(type,d)}</div><br><button class="btn primary" onclick="window.print()">Print / PDF</button> <button class="btn ghost" onclick="App.copyText('${type}','${id}')">Copy WhatsApp Text</button>`); },
  printHtml(type,d){ const rows=(d.items||[]).map(i=>`<tr><td>${i.description}</td><td>${i.qty}</td><td>${Logic.money(i.price)}</td><td>${Logic.money(Number(i.qty)*Number(i.price))}</td></tr>`).join(''); return `<div class="print-brand"><div><h1>GM Security Systems</h1><p>Security · CCTV · Network · IT</p></div><div><h2>${d.id}</h2><p>${d.date||''}</p></div></div><p><b>Client:</b> ${d.client}</p>${rows?`<table class="print-table" width="100%"><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Total</th></tr></thead><tbody>${rows}</tbody></table>`:''}<h2 class="right">Total: ${Logic.money(d.total||d.amount)}</h2><p>${d.notes||d.terms||''}</p>` },
  copyText(type,id){ const list=type==='quote'?'quotes':type==='invoice'?'invoices':'receipts'; const d=this.data[list].find(x=>x.id===id); const txt=`GM Security Systems\n${type.toUpperCase()}: ${d.id}\nClient: ${d.client}\nTotal: ${Logic.money(d.total||d.amount)}\nThank you.`; navigator.clipboard?.writeText(txt); this.toast('Copied WhatsApp text'); },
  statement(client){ const inv=this.data.invoices.map(Logic.normalizeInvoice).filter(i=>i.client===client), rec=this.data.receipts.filter(r=>r.client===client); const total=inv.reduce((a,i)=>a+i.total,0), paid=rec.reduce((a,r)=>a+Number(r.amount),0), bal=total-paid; this.modal('Statement of Account',`<div class="print-area"><div class="print-brand"><h1>GM Security Systems</h1><h2>Statement</h2></div><p><b>Client:</b> ${client}</p><p>Total Invoiced: ${Logic.money(total)} | Total Paid: ${Logic.money(paid)} | Balance: ${Logic.money(bal)}</p><h3>Invoices</h3>${inv.map(i=>this.listRow(i.id,i.date,Logic.money(i.total),i.status)).join('')}<h3>Receipts</h3>${rec.map(r=>this.listRow(r.id,r.date,Logic.money(r.amount),r.method)).join('')}</div><br><button class="btn primary" onclick="window.print()">Print Statement</button>`); },
  edit(type,id){ if(type==='quote')this.openDocForm('quote',id); if(type==='invoice')this.openDocForm('invoice',id); },
  del(type,id){ if(!confirm('Delete?'))return; const map={quote:'quotes',invoice:'invoices'}; this.data[map[type]]=this.data[map[type]].filter(x=>x.id!==id); this.save(); this.render(); },
  openSettings(){this.go('settings')},
  exportBackup(){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(this.data,null,2)],{type:'application/json'})); a.download='gm-security-backup-'+Logic.today()+'.json'; a.click(); },
  importBackup(e){ const f=e.target.files[0]; if(!f)return; const r=new FileReader(); r.onload=()=>{this.data=JSON.parse(r.result);this.save();this.render();this.toast('Backup imported')}; r.readAsText(f); },
  resetDemo(){ if(confirm('Reset all demo data?')){localStorage.removeItem('gm_data_v4');this.load();this.render();} }
};
if(typeof document!=='undefined') document.addEventListener('DOMContentLoaded',()=>App.init());
if(typeof module!=='undefined') module.exports={Logic};
